### ISSUE TITLE
sashik_eth - Set could be forced to isolation mode

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#103]
sashik_eth

medium

# Set could be forced to isolation mode

## Summary

Set could be forced to isolation mode.

## Vulnerability Detail

One of the new features of Aave v3 is "isolation mode". It allows making some assets "isolated" from other resources in the pool. When borrowers supply isolated assets as collateral they automatically become unable to use other assets as collateral.

Since Aave would set assets as collateral during [transferring](https://github.com/aave/aave-v3-core/blob/v1.17.2/contracts/protocol/libraries/logic/SupplyLogic.sol#L222), this opens a potential attack vector when the attacker transfers some amount of isolated asset to a newly created Set address (or upfront since all Sets are created through the factory and its addresses are predictable). After this isolated asset becomes Set's collateral and Set becomes unable to provide other assets as collateral, this basically blocks `AaveV3LeverageModule` core functionality.

To mitigate such a situation manager could call `AaveV3LeverageModule#removeCollateralAssets` providing a "poisoned" asset address in parameters, previously called `AaveV3LeverageModule#addCollateralAssets` to add this address to the `collateralAssetEnabled` list, otherwise would be impossible to disable asset as collateral for Set.

Manager functionality is handled by the `methodologist` and `operator` through the `BaseManagerV2` contract and its extensions. `AaveV3LeverageStrategyExtension` does not have appropriate functions that would allow the required calls to mitigate the problem (`addCollateralAssets` and `removeCollateralAssets` could not be called through this extension). So to execute appropriate calls `methodologist` and `operator` would need to transfer the manager role to some EOA/wallet address. 

In some other edge cases, Set could be forced to isolation mode if at the moment Set has only one asset and it's isolated or Aave admins make it isolated, check reference issue (5.2.5):
https://github.com/spearbit/portfolio/blob/master/pdfs/Morpho-Av3-Spearbit-Security-Review.pdf

## Impact

Anyone could "poison" a newly created Set or any not yet deployed Set upfront by sending some amount of Aave isolated asset. This would force Set to isolation mode preventing from using other assets as collateral, basically broking protocol functionality. Mitigation would require trusted actors (`methodologist` and `operator`) to break the existing trust model and transfer the core role (`manager`) to some external EOA/wallet.

## Code Snippet

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L1019

## Tool used

Manual Review

## Recommendation

Consider adding to `AaveV3LeverageStrategyExtension` 2 functions: one to allow the operator to call `AaveV3LeverageModule#addCollateralAssets` and another to call `AaveV3LeverageModule#removeCollateralAssets`. Alternatively, consider adding a permissionless function that does these two calls only in case if "poisoned" asset is not in the list of enabled Set collaterals.

**Comment by sashik-eth** [comment]
Escalate for 10 USDC
Would like to know why this was excluded

**Comment by IAm0x52** [comment]
Invalid. Which assets are used as collateral can be disabled via [this function](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AaveLeverageModule.sol#L1006-L1073) which prevents this issue

**Comment by sashik-eth** [comment]
@IAm0x52 The problem is that `methodologist` and `operator` would not be able to call this function through `AaveV3LeverageStrategyExtension`:

> To mitigate such a situation manager could call `AaveV3LeverageModule#removeCollateralAssets` providing a "poisoned" asset address in parameters, previously called `AaveV3LeverageModule#addCollateralAssets` to add this address to the `collateralAssetEnabled` list, otherwise would be impossible to disable asset as collateral for Set.

> Manager functionality is handled by the `methodologist` and `operator` through the `BaseManagerV2` contract and its extensions. `AaveV3LeverageStrategyExtension` does not have appropriate functions that would allow the required calls to mitigate the problem (`addCollateralAssets` and `removeCollateralAssets` could not be called through this extension). So to execute appropriate calls `methodologist` and `operator` would need to transfer the manager role to some EOA/wallet address.

**Comment by Evert0x** [comment]
Is this is a similar issue as #164?

@0xffff11 what are your thought on it?

**Comment by 0xffff11** [comment]
I think they can be dups yes. As states by Lead Watson, the "admin" would be able to revert this state by calling the `_updateUseReserveAsCollateral` , which is the same "revert scenario" than in issue #164 I think it can be a low

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Based on the discussion in #164 considering this issue a low
https://github.com/sherlock-audit/2023-05-Index-judging/issues/164#issuecomment-1656107885

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [sashik-eth](https://github.com/sherlock-audit/2023-05-Index-judging/issues/103/#issuecomment-1610055675): rejected
