### ISSUE TITLE
ast3ros - Unbounded loops in AaveV3LeverageModule may cause DOS

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#136]
ast3ros

medium

# Unbounded loops in AaveV3LeverageModule may cause DOS

## Summary

The AaveV3LeverageModule allows the SetToken manager to add and have positions in any number of collateral and borrow tokens. However, this may cause some functions in the module to revert or fail due to unbounded loops that consume a lot of gas.

## Vulnerability Detail

The AaveV3LeverageModule has functions such as `addCollateralAssets` and `addBorrowAssets` that enable the SetToken manager to add any number of collateral and borrow tokens.

        function addCollateralAssets(ISetToken _setToken, IERC20[] memory _newCollateralAssets) external onlyManagerAndValidSet(_setToken) { 
            _addCollateralAssets(_setToken, _newCollateralAssets);
        }

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L598-L600

        function addBorrowAssets(ISetToken _setToken, IERC20[] memory _newBorrowAssets) external onlyManagerAndValidSet(_setToken) {
            _addBorrowAssets(_setToken, _newBorrowAssets);
        }

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L627-L629

However, there are some functions in the module that loop through the list of collateral and borrow tokens to perform certain actions. For example:

- Sync: updates the state of all collateral and borrow positions

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L444
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L457

- removeModule: unwinds all collateral and borrow positions before removing the module

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L521
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L530

These functions may revert or fail if the number of collateral and borrow tokens is too large. This is because they may use a lot of gas when there are a lot of users (especially on mainnet) or exceed the block gas limit. This may lead to a denial-of-service (DOS).

## Impact

The unbounded loops may affect the functionality and security of the AaveV3LeverageModule and the SetToken. For example, if the `sync` function fails, it may disrupt the `issue` and `redeem` process of the SetToken since the `moduleIssueHook` and `moduleRedeemHook` call `sync` to update all position states.

## Code Snippet

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L505-L506
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L598-L600
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L627-L629
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L444
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L457
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L521
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L530

## Tool used

Manual Review

## Recommendation

Limit the number of collateral and borrow tokens that a SetToken can have positions on. The admin can set an upper bound for this number and enforce it in the `addCollateralAssets` and `addBorrowAssets` functions. Alternatively, refactor the functions that use loops to use batches or pagination instead.

**Comment by thangtranth** [comment]
Escalate for 10 USDC

Please help to recheck this issue since it can break the functionality of the protocol

**Comment by stalinMacias** [comment]
@thangtranth 
I think the reason why this issue was excluded is that the functions that have been reported are admin functions, so, the admins are responsible for managing the collateralAssets and borrowAssets, this would be a type of self wreck but caused by the admin, and since the admin is trusted it is assumed they won't engage on causing DoS, this would probably be low/informational, but let's see what Sherlock think about it

**Comment by IAm0x52** [comment]
Low. Admin manages this functionality and should be expected to be competent enough to keep loop size under control so they don't DOS the set token.

**Comment by stalinMacias** [comment]
Agree with the reason, thanks for the answer @IAm0x52 
Question: if this is marked as low, does that mean that the escalation and the issue won't be penalized?

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with Lead Watson's comment. Considering this a valid low.
