### ISSUE TITLE
ast3ros - Disengage function does not prevent iterateRebalance from being called

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#137]
ast3ros

medium

# Disengage function does not prevent iterateRebalance from being called

## Summary

The operator can call the `disengage` function in the AaveLeverageStrategyExtension to unwind the leveraged position. However, this function does not clear the `twapLeverageRatio` state variable, which allows the `iterateRebalance` function to be called. If the extension is set up for anyone to call, anyone can call the iterateRebalance function to increase the leverage ratio and prevent the strategy from being shut down by the operator.

## Vulnerability Detail

The `disengage` function in the `AaveLeverageStrategyExtension` allows the operator to unwind the leveraged position by repaying the debt and withdrawing the collateral.

        function disengage(string memory _exchangeName) external onlyOperator {...}

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L412-L438

The design is described in the Natspec:
        
        If chunk rebalance size is above max borrow or max trade size, then operator must continue to call this function to complete repayment of loan. The function iterateRebalance will not work.

However, if the strategy is in TWAP, the `disengage` function does not clear the `twapLeverageRatio` state variable. This means that the `iterateRebalance` function can still be called if certain conditions are met.

In the scenario, after calling the `disengage` function, if the current leverage ratio is between 1 and `minLeverageRatio`, the `iterateRebalance` function can be called multiple times to bring the leverage ratio back to `minLeverageRatio`.

        function _validateNormalRebalance(LeverageInfo memory _leverageInfo, uint256 _coolDown, uint256 _lastTradeTimestamp) internal view {
            require(_leverageInfo.currentLeverageRatio < incentive.incentivizedLeverageRatio, "Must be below incentivized leverage ratio");
            require(
                block.timestamp.sub(_lastTradeTimestamp) > _coolDown
                || _leverageInfo.currentLeverageRatio > methodology.maxLeverageRatio
                || _leverageInfo.currentLeverageRatio < methodology.minLeverageRatio, // @audit if current leverage ratio < min leverage ratio, then the iterateRebalance can be call without cooldown.
                "Cooldown not elapsed or not valid leverage ratio"
            );
        }

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L970-L978

If the extension is set up for anyone to call (when anyoneCallable = true), anyone can call the `iterateRebalance` function to increase the leverage ratio and stop the strategy from being shut down by the operator.

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L338

## Impact

The iterateRebalance function can still be called when disengaging, which violates the design. In case the extension is set up for anyone to call, it may prevent disengaging.

## Code Snippet

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L412-L438
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L970-L978
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L338

## Tool used

Manual Review

## Recommendation

Set a state variable `disengaging = true` when operator disengages, and check if `disengaging = true` then do not allow to call `rebalance` or `iterateRebalance`.

**Comment by thangtranth** [comment]
Escalate for 10 USDC

This is a valid issue that can be use to break the intended design of the protocol and prevent operator from `disengage`. Please help to review.

**Comment by ckoopmann** [comment]
Disengage should result in `borrowBalance` being zero which will trigger a revert in the `_getAndValidateLeverageInfo` call inside `iterateRebalance`.

Therefore I think this issue is not correct and it is not possible to call `iterateRebalance` on a disengaged token

**Comment by hrishibhat** [comment]
@thangtranth any further comments on the issue?

**Comment by thangtranth** [comment]
The borrow balance is only becoming zero if `totalRebalanceNotional <= chunkRebalanceNotional`. Otherwise operator has to call the function disengage multiple time to repay all the borrowBalance. 

You can see it in this snippet of code :
```
        if (totalRebalanceNotional > chunkRebalanceNotional) {
            _delever(leverageInfo, chunkRebalanceNotional);
        } else {
            _deleverToZeroBorrowBalance(leverageInfo, totalRebalanceNotional);
        }
```

https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L426-L430

If `totalRebalanceNotional > chunkRebalanceNotional` then it only delevered to reduce the debt, and anyone can call `iterateRebalance`

**Comment by Evert0x** [comment]
@0xffff11 any thoughts on this escalation?

**Comment by hrishibhat** [comment]
@ckoopmann

**Comment by 0xffff11** [comment]
@thangtranth I see that even if `totalRebalanceNotional > chunkRebalanceNotional` operator  can still  make `borrowBalance` to be zero by calling disengage multiple times, so this would not happen?

**Comment by thangtranth** [comment]
@0xffff11 Yes, the operator has to call the disengage multiple times. So it is not an atomic transaction. And if `anyoneCallable` is set to true then between the disengage calls, anyone can call `iterateRebalance` to bring it up and prevent the disengage.

Therefore in my recommendation, I suggest that adding a variable that indicates that the disengagement process is in progress, so no one can call any function to increase the debt.

**Comment by 0xffff11** [comment]
I see, seems a valid concern then. I don't see a medium impact though if the consequences is a design violation, or operator not being able to call a function.

**Comment by thangtranth** [comment]
@0xffff11 The impact is that a malicious user can prevent the operator from disengaging and repaying the debt. This leads to the operator being unable to shut down the strategy. The consequences can be severe in times of high downside volatility, which can result in losses. And I believe this is not the intention of the protocol to be in the state.

I think that the vulnerability deserves a medium issue, as it could have serious implications for the operator and the index.

**Comment by ckoopmann** [comment]
The operator can set `anyoneCallable` to false if he observes this issue and avoid other users from interfering with the disengage in the described way. 

Therefore this seems to be of "low / informational" priority max.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low based on the impact described by the Sponsor.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [thangtranth](https://github.com/sherlock-audit/2023-05-Index-judging/issues/137/#issuecomment-1610590421): rejected
