### ISSUE TITLE
ast3ros - Methodology settings can be changed by operator instead of methodologist

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#138]
ast3ros

medium

# Methodology settings can be changed by operator instead of methodologist

## Summary

The AaveV3LeverageModule contract allows the operator to change the methodology settings that define the token strategy. However, according to the role description, this should be done by the methodologist.

## Vulnerability Detail

In the role description in audit channel, operator and methodologist roles are defined as:

        - Operator:
        The party that is responsible for "day to day management" of the set token. Often this means ensuring that the set token is regularily rebalanced to adhere to a certain strategy.

        - Methodologist:
        Sets and controls the parameter that define a set tokens strategy and put guardrails on the actions of the Operator.
        While those two roles could be held by the same party, for some of our products we will have an external partner act as Methodologist.

However, in the AaveV3LeverageModule contract, the function to set methodology `setMethodologySettings` can only be called by the operator instead of the methodologist.

        function setMethodologySettings(MethodologySettings memory _newMethodologySettings) external onlyOperator noRebalanceInProgress {
            methodology = _newMethodologySettings;

            _validateNonExchangeSettings(methodology, execution, incentive);

            emit MethodologySettingsUpdated(
                methodology.targetLeverageRatio,
                methodology.minLeverageRatio,
                methodology.maxLeverageRatio,
                methodology.recenteringSpeed,
                methodology.rebalanceInterval
            );
        }

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L446-L458

This means that the operator can change the parameters that define the token strategy without any input or restriction from the methodologist.

## Impact

The operator has more authority than defined in the role and does not have any guardrails from the methodologist.

## Code Snippet

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L446-L458

## Tool used

Manual Review

## Recommendation

Change the modifier from `onlyOperator` to `onlyMethodologist` in the `setMethodologySettings` function.

```diff
-        function setMethodologySettings(MethodologySettings memory _newMethodologySettings) external onlyOperator noRebalanceInProgress {
+        function setMethodologySettings(MethodologySettings memory _newMethodologySettings) external onlyMethodologist noRebalanceInProgress {
```

**Comment by thangtranth** [comment]
Escalate for 10 USDC

This is a valid issue since it breaks the role based design of the contract. Please help to review.

**Comment by Evert0x** [comment]
@0xffff11 sounds like a valid issue, what do you think?

**Comment by ckoopmann** [comment]
The Operator being able to set these parameters is the expected behaviour for how we will run this product. However I can see how from the naming of the `methodologySettings` one would expect them to be set by the "Methodologist".

I will therefore set this as "confirmed" but "wont fix".

**Comment by thangtranth** [comment]
I think this is not just about the name of the function setMethodologySettings. The state variable `methodology` in the function contains all the methodology configuration:

https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L447

https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L98-L104

Therefore, it contradicts the responsibility defined for the role and it is a valid “access control and privilege escalation” issue in the contest scope:

>   - Methodologist:
    Sets and controls the parameter that define a set tokens strategy and put guardrails on the actions of the Operator.

**Comment by 0xStalin-eth** [comment]
I believe what the sponsor is saying is that the operator is the one that sets the parameters of the methodologist, that means that the methodologist will be bounded by what the operator decides.
Or in other words, the methodologists are not allowed to set their own parameters, that's why the onlyOperator() modifier is used.
Please @ckoopmann , correct me if I'm wrong

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Although understandably confusing with the naming, This seems to be working as expected.
https://docs.tokensets.com/developers/contracts/strategies/deltaneutralbasistradingstrategy#setmethodologysettings

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [thangtranth](https://github.com/sherlock-audit/2023-05-Index-judging/issues/138/#issuecomment-1610618086): rejected
