### ISSUE TITLE
Saeedalipoor01988 - Lack of check the data returned from getReserveConfigurationData function in AAVE3

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#143]
Saeedalipoor01988

medium

# Lack of check the data returned from getReserveConfigurationData function in AAVE3

## Summary
Lack of check of the data returned from [AaveProtocolDataProvider.getReserveConfigurationData function](https://github.com/aave/aave-v3-core/blob/master/contracts/misc/AaveProtocolDataProvider.sol#L83) in the [strategy.aaveProtocolDataProvider.getReserveConfigurationData function](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L1098).

## Vulnerability Detail
```solidity
  function getReserveConfigurationData(
    address asset
  )
    external
    view
    override
    returns (
      uint256 decimals,
      uint256 ltv,
      uint256 liquidationThreshold,
      uint256 liquidationBonus,
      uint256 reserveFactor,
      bool usageAsCollateralEnabled,
      bool borrowingEnabled,
      bool stableBorrowRateEnabled,
      bool isActive,
      bool isFrozen
    )
```

The above code is the getReserveConfigurationData function that returns data related to asset reserve configuration. the AaveLeverageStrategyExtension.sol._calculateMaxBorrowCollateral() function is using the above function to calculate the max borrow / repay the amount allowed in base units for lever / delever.

```solidity
// Retrieve collateral factor and liquidation threshold for the collateral asset in precise units (1e16 = 1%)
        ( , uint256 maxLtvRaw, uint256 liquidationThresholdRaw, , , , , , ,) = strategy.aaveProtocolDataProvider.getReserveConfigurationData(address(strategy.collateralAsset));
```

After getting the maxLtvRaw value and liquidationThresholdRaw value from AaveProtocolDataProvider.getReserveConfigurationData function, there is no check whether these values are zero or not. these values for USDT are 0 and for AAVE token are not.

```solidity
USDT data :
  decimals   uint256 :  6
  ltv   uint256 :  0
  liquidationThreshold   uint256 :  0
  liquidationBonus   uint256 :  0
  reserveFactor   uint256 :  1000
  usageAsCollateralEnabled   bool :  false
  borrowingEnabled   bool :  true
  stableBorrowRateEnabled   bool :  false
  **isActive   bool :  true
  isFrozen   bool :  false**
```

```solidity
AAVE data:
  decimals   uint256 :  18
  ltv   uint256 :  6600
  liquidationThreshold   uint256 :  7300
  liquidationBonus   uint256 :  10750
  reserveFactor   uint256 :  0
  usageAsCollateralEnabled   bool :  true
  borrowingEnabled   bool :  false
  stableBorrowRateEnabled   bool :  false
  **isActive   bool :  true
  isFrozen   bool :  false**
```

This issue is important when the [setManager function](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/SetToken.sol#L420) change manager to a null address and there is no control over the functions of adding or removing collateral / Borrow assets.

```solidity
    /**
     * MANAGER ONLY. Changes manager; **We allow null addresses** in case the manager wishes to wind down the SetToken.
     * Modules may rely on the manager state, so only changable when unlocked
     */
    function setManager(address _manager) external onlyManager {
        require(!isLocked, "Only when unlocked");
        address oldManager = manager;
        manager = _manager;

        emit ManagerEdited(_manager, oldManager);
    }
```

## Impact
Underflow revert in AaveLeverageStrategyExtension.sol._calculateMaxBorrowCollateral() function could disable the functionality of the protocol.

## Code Snippet
https://github.com/aave/aave-v3-core/blob/master/contracts/misc/AaveProtocolDataProvider.sol#L83

https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L1098

https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/SetToken.sol#L417

https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L597
https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L607
https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L627
https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L637

## Tool used
Manual Review

## Recommendation
check the data returned from AaveProtocolDataProvider.getReserveConfigurationData function.

**Comment by saeedalipoorcom** [comment]
Escalate for 10 USDC

I think this issue should be duplicate of [#159](https://github.com/sherlock-audit/2023-05-Index-judging/issues/159).

This issue impact : **Underflow revert in AaveLeverageStrategyExtension.sol._calculateMaxBorrowCollateral() function.** because of LTV = 0.

This issue impact [#159](https://github.com/sherlock-audit/2023-05-Index-judging/issues/159) : 
**The LTV = 0 causing underflow in the _calculateMaxBorrowCollateral() function.**

Thanks

**Comment by hildingr** [comment]
This is not a duplicate of #159. LTV can be changed to 0 for any collateral and that will block all other positions that is why it is an issue. This has nothing to do with that.

**Comment by saeedalipoorcom** [comment]
> This is not a duplicate of #159. LTV can be changed to 0 for any collateral and that will block all other positions that is why it is an issue. This has nothing to do with that.

Yes you are right ! Let the judges take it from here.

**Issue #159,** 
When an AToken has LTV = 0, Aave restricts the usage of certain operations. Specifically, if a user owns at least one AToken as collateral with an LTV = 0. 

When LTV = 0, maxLtvRaw also equals 0, leading to a netBorrowLimit of 0. When the borrowing value is subtracted from this, it results in an underflow.

**here i mentioned,**

```solidity
// Retrieve collateral factor and liquidation threshold for the collateral asset in precise units (1e16 = 1%)
        ( , uint256 maxLtvRaw, uint256 liquidationThresholdRaw, , , , , , ,) = strategy.aaveProtocolDataProvider.getReserveConfigurationData(address(strategy.collateralAsset));
```

After getting the maxLtvRaw value or ltv value and liquidationThresholdRaw value from AaveProtocolDataProvider.getReserveConfigurationData function, there is no check whether these values are zero or not, and result is Underflow.

Recommendation : check the data returned from AaveProtocolDataProvider.getReserveConfigurationData function.

**Comment by hildingr** [comment]
Not sure what you are saying here. Checking the return value does nothing to mitigate that another component has been set ltv=0. Read [this](https://github.com/sherlock-audit/2023-05-Index-judging/issues/159#issuecomment-1600066030) by the client and #315 for the actual issue of LTV=0.

**Comment by saeedalipoorcom** [comment]
> Not sure what you are saying here. Checking the return value does nothing to mitigate that another component has been set ltv=0. Read [this](https://github.com/sherlock-audit/2023-05-Index-judging/issues/159#issuecomment-1600066030) by the client and #315 for the actual issue of LTV=0.

i think you should use Escalate for 10 USDC.

**Comment by Evert0x** [comment]
@0xffff11 it seems to me that `hildingr` is correct in his assessment and the escalation should be rejected, what do you think?

**Comment by 0xffff11** [comment]
Yes, the report of @saeedalipoorcom  is not describing the same as #159  and the impact of not checking the data is not worth a medium. I would reject the escalation

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with the disputing comments above as the issue does not clearly describe a medium impact nor the descriptions is clear enough for issue to be considered a duplicate of #159 for the actual issue mentioned [here](https://github.com/sherlock-audit/2023-05-Index-judging/issues/159#issuecomment-1600066030)

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [saeedalipoorcom](https://github.com/sherlock-audit/2023-05-Index-judging/issues/143/#issuecomment-1610394924): rejected
