### ISSUE TITLE
Bauchibred - DebtIssuanceModuleV2.sol: Current Implementenation of `_resolveEquityPositions()` and `_resolveDebtPositions()` causes Potential issues when Dealing with Some Tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#154]
Bauchibred

medium

# DebtIssuanceModuleV2.sol: Current Implementenation of `_resolveEquityPositions()` and `_resolveDebtPositions()` causes Potential issues when Dealing with Some Tokens

## Summary

Two functions, `_resolveEquityPositions()` and `_resolveDebtPositions()` in the updated [DebtIssuanceModuleV2.sol](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/DebtIssuanceModule.sol#L4), usage of `invokeTransfer()` instead of the `strictInvokeTransfer()` method to transfer tokens is implemented. With this update unlike the old version of [DebtIssuanceModule.sol](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/DebtIssuanceModule.sol#L137) where `strictInvokeTransfer()` was being used, now there is no protection against fee on transfer tokens and if these tokens are to be allowed inprotocol they could easily break the accounting logic.

## Vulnerability Detail

In both functions, i.e
[Take a look at DebtIssuanceModuleV2.sol#L251-L333](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/DebtIssuanceModuleV2.sol#L251-L333)

```solidity
    function _resolveEquityPositions(
        ISetToken _setToken,
        uint256 _quantity,
        address _to,
        bool _isIssue,
        address[] memory _components,
        uint256[] memory _componentEquityQuantities,
        uint256 _initialSetSupply,
        uint256 _finalSetSupply
    )
        internal
    {
//ommited for brevity
                } else {
                    _executeExternalPositionHooks(_setToken, _quantity, IERC20(component), false, true);

                    // Call Invoke#invokeTransfer instead of Invoke#strictInvokeTransfer
                    _setToken.invokeTransfer(component, _to, componentQuantity);

//ommited for brevity
                }
            }
        }
    }



    function _resolveDebtPositions(
        ISetToken _setToken,
        uint256 _quantity,
        bool _isIssue,
        address[] memory _components,
        uint256[] memory _componentDebtQuantities,
        uint256 _initialSetSupply,
        uint256 _finalSetSupply
    )
        internal
    {
//ommited for brevity

                    // Call Invoke#invokeTransfer instead of Invoke#strictInvokeTransfer
                    _setToken.invokeTransfer(component, msg.sender, componentQuantity);

                    IssuanceValidationUtils.validateCollateralizationPostTransferOut(_setToken, component, _finalSetSupply);
//ommited for brevity
                }
            }
        }
    }
```

As seen both functions now use Invoke#invokeTransfer instead of Invoke#strictInvokeTransfer
The method `strictInvokeTransfer()` has a mechanism that ensures the final balance of the token is equivalent to the initial balance minus the quantity transferred. This would help in this case as it ensures that if the token being transferred has a transfer fee or is a deflationary token, the transfer wouldn't go through and the balance check would fail.

Now take a look at [Invoke.sol#L66-L112](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/lib/Invoke.sol#L58-L112)

```solidity
    /**
     * Instructs the SetToken to transfer the ERC20 token to a recipient.
     *
     * @param _setToken        SetToken instance to invoke
     * @param _token           ERC20 token to transfer
     * @param _to              The recipient account
     * @param _quantity        The quantity to transfer
     */
    function invokeTransfer(
        ISetToken _setToken,
        address _token,
        address _to,
        uint256 _quantity
    )
        internal
    {
        if (_quantity > 0) {
            bytes memory callData = abi.encodeWithSignature("transfer(address,uint256)", _to, _quantity);
            _setToken.invoke(_token, 0, callData);
        }
    }

    /**
     * Instructs the SetToken to transfer the ERC20 token to a recipient.
     * The new SetToken balance must equal the existing balance less the quantity transferred
     *
     * @param _setToken        SetToken instance to invoke
     * @param _token           ERC20 token to transfer
     * @param _to              The recipient account
     * @param _quantity        The quantity to transfer
     */
    function strictInvokeTransfer(
        ISetToken _setToken,
        address _token,
        address _to,
        uint256 _quantity
    )
        internal
    {
        if (_quantity > 0) {
            // Retrieve current balance of token for the SetToken
            uint256 existingBalance = IERC20(_token).balanceOf(address(_setToken));

            Invoke.invokeTransfer(_setToken, _token, _to, _quantity);

            // Get new balance of transferred token for SetToken
            uint256 newBalance = IERC20(_token).balanceOf(address(_setToken));

            // Verify only the transfer quantity is subtracted
            require(
                newBalance == existingBalance.sub(_quantity),
                "Invalid post transfer balance"
            );
        }
    }

```

However, it is noted that there are no FEE-ON-TRANSFER tokens interacting with the smart contracts currently. But if there are plans to introduce such tokens in the future, the current implementation of `strictInvokeTransfer()` would cause issues.
The above paragraph is coined from one of the Q/A by sponsors which validates issule
[Discussion](https://github.com/sherlock-audit/2023-05-Index/tree/3190057afd3085143a31746d65045a0d1bacc78c#q-are-there-any-fee-on-transfer-tokens-interacting-with-the-smart-contracts)

```diff
Q: Are there any FEE-ON-TRANSFER tokens interacting with the smart contracts?
A: Not at the moment, but it would be good to know if they can interact with our smart contracts
```

## Impact

Inability to integrate Fee-on-transfer tokens in the future

## Code Snippet

[DebtIssuanceModuleV2.sol#L251-L333](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/DebtIssuanceModuleV2.sol#L251-L333)

## Tool used

Manual review

## Recommendation

If there are plans of integrating fee-on transfer tokens in the future then integrate correct acccounting mesure to know the exact amount of tokens thst are being accounted for

**Comment by Bauchibred** [comment]
Escalate for 10 USDC

Following the discussions on #61 I'd like this issue to be re-checked, cause as far as I remember the protocol clearly stated that they are welcoming findings related to Fee-On-Transfer tokens from this section of the contest readMe's  [Q&A](https://github.com/sherlock-audit/2023-05-Index/tree/3190057afd3085143a31746d65045a0d1bacc78c#q-are-there-any-fee-on-transfer-tokens-interacting-with-the-smart-contracts)

**Comment by 0xffff11** [comment]
I think it should be considered a duplicate of #61 The issue is not exactly the same, but the point is the same fee-on-transfer are not supported. After seeing this issue I would consider #61 a medium and duplicate this one too.

**Comment by hrishibhat** [comment]
Result:
Low
Unique 
While the statement in the readme can be open to interpretations, it clearly mentions that the code is not designed to support Fee-On-Transfer tokens in its current state.
Considering this a low issue.
