### ISSUE TITLE
Bauchibred - Invoke Library: Lack of Return Value Checks in ERC20 operations

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#155]
Bauchibred

medium

# Invoke Library: Lack of Return Value Checks in ERC20 operations

## Summary

The `Invoke` library in the project lacks return value checks in ERC20 transfers/approvals. This could lead to silent failures and incorrect internal accounting.

## Vulnerability Detail

The vulnerability arises from the following code snippets in the [Invoke.sol](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/lib/Invoke.sol#L1-L136) library:

```solidity
function invokeApprove(ISetToken _setToken, address _token, address _spender, uint256 _quantity)
    internal
{
    // @audit the return value of the execution is not checked

    bytes memory callData = abi.encodeWithSignature("approve(address,uint256)", _spender, _quantity);
    _setToken.invoke(_token, 0, callData);
}

function invokeTransfer(ISetToken _setToken, address _token, address _to, uint256 _quantity)
    internal
{
    // @audit the return value of the execution is not checked

    if (_quantity > 0) {
        bytes memory callData = abi.encodeWithSignature("transfer(address,uint256)", _to, _quantity);
        _setToken.invoke(_token, 0, callData);
    }
}

function strictInvokeTransfer(ISetToken _setToken, address _token, address _to, uint256 _quantity)
    internal
{
    // @audit same thing
    if (_quantity > 0) {
        uint256 existingBalance = IERC20(_token).balanceOf(address(_setToken));
        Invoke.invokeTransfer(_setToken, _token, _to, _quantity);
        uint256 newBalance = IERC20(_token).balanceOf(address(_setToken));
        require(newBalance == existingBalance.sub(_quantity), "Invalid post transfer balance");
    }
}
```

The code snippets show that the return values of ERC20 operations are not checked. This can result in silent failures and incorrect internal accounting.

## Impact

The lack of return value checks in ERC20 operations can lead to silent failures. For example if a transfer fails, it will not be detected, resulting in incorrect internal accounting.

## Code Snippet

[Invoke.sol](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/lib/Invoke.sol#L1-L136) library:

## Tool used

Manual Review

## Recommendation

To address this vulnerability, it is recommended to implement return value checks for all ERC20 transfers/approvals in the `Invoke` library. By checking the return values, the library can detect transfer failures and handle them appropriately, ensuring accurate internal accounting.

One recommended approach is to use the SafeERC20 library provided by OpenZeppelin. The library includes safe versions of ERC20 transfer functions that handle return value checks and revert the transaction if the transfer fails. Integrating the SafeERC20 library will enhance the robustness of the token transfer operations in the `Invoke` library.

Duplicate of #169

**Comment by Bauchibred** [comment]
Hi @hrishibhat  I believe this issue has been wrongly tagged non-reward, due it's former duplication, but following the arguments in  [1](https://github.com/sherlock-audit/2023-05-Index-judging/issues/169#issuecomment-1627700526), [2](https://github.com/sherlock-audit/2023-05-Index-judging/issues/280#issuecomment-1610634769) & [3](https://github.com/sherlock-audit/2023-05-Index-judging/issues/236#issuecomment-1610361789), this issue should be valid and have the same fate as the aforementioned ones.
