### ISSUE TITLE
shogoki - DoS - No Issuance / Borrowing possible because of AAVEv3 Isolation mode.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#164]
shogoki

medium

# DoS - No Issuance / Borrowing possible because of AAVEv3 Isolation mode.

## Summary

An attacker or malicous user can force the AAVE position of the setToken to AAVEv3 Isolation mode. This will prevent the contract from enabling other Assets as Collateral, and borrowing of some tokens and therefore finally issuance of new Tokens.

## Vulnerability Detail

AAVEv3 introduced Isolation mode, which `allows to list new assets as Isolated which has a specific debt ceiling and can be only used to borrow stablecoins that have been permitted, by Aave Governance, to be borrowable in isolation mode.`
Therefore when the position is in Isolation mode and the in AAVEv3LeverageModule defined Collateral/Borrow Assets do not match the criteria they cannot be used as Collateral/borrowed. 

An Attacker can force the position into Isolation Mode by supplying an (small) amount of an isolated Asset on behalf of the target `SetToken`, when it is holding no other aTokens (yet). (AAVev3´s supply funcion allows supplying for other recpients). This will result in the `SetToken` contract to receive the corresponding aToken. If this is the first aToken for the Address (SetToken Contract) AAVe will automatically enable it as collateral, and in case it is an isolated asset enable Isolation mode. (see [AAve DOcs](https://docs.aave.com/developers/whats-new/isolation-mode))

As the DebtIssuanceModulev2 is used to issue Tokens and the registered component Hooks inside the `ÀAveV3LeverageModule`invoke a borrow call on AAve (which probably fails) it is not anymore possible to issue any Tokens.

## Impact

- No new SetTokens can be issued
- SetToken cannot borrow more Tokens on AAVE
  
## Code Snippet

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L695-L706

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L786-L788

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L778-L780

## Tool used

Manual Review

## Recommendation

Check if there are other aTokens, than the enabled Collateral Tokens in the Contract, and if yes, mark them as not to be used as collateral

**Comment by Shogoki** [comment]
Escalate for 10USDC
This should be considered valid. 
AAVE isolation mode is similiar to LTV=0 assets, which got accepted: #159

**Comment by 0xffff11** [comment]
Issues seems valid to me. I would agree with a medium. Thoughts? @ckoopmann

**Comment by Evert0x** [comment]
@IAm0x52 what are your thoughts on this? Is this a legit attack?

**Comment by IAm0x52** [comment]
Low IMO. Only possible at the very beginning of a set token when the set has no other tokens. As soon as it holds any other aToken this is impossible. Worst case the set token is simply redeployed

**Comment by Shogoki** [comment]
> Low IMO. Only possible at the very beginning of a set token when the set has no other tokens. As soon as it holds any other aToken this is impossible. Worst case the set token is simply redeployed

Still think it should be considered Medium. 
An attacker can easily and with minimum cost DoS the SetToken. Not only for new Tokens, but also for existing ones, when there are temporarily no other aTokens (all SetTokens redeemed), which makes the simple redeploy more complicated as the Token is maybe already known/in use.

Please also take a look at this [Spearbit Audit Report Finding 5.2.5](https://cdn.morpho.xyz/documents/Spearbit_04052023.pdf) where a similiar issue was considered as High.

**Comment by IAm0x52** [comment]
This only affects tokens using baseManager, since an EOA manager can simply disable the collateral via [this function](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AaveLeverageModule.sol#L1006-L1073). Once disabled it can never be triggered again. For set tokens utilizing baseManger they could simply transfer to an EOA, disable and transfer back to baseManager. Still recommending low for this because it's inconvenient but still easily fixed without any loss and short downtime if any.

**Comment by Shogoki** [comment]
> This only affects tokens using baseManager, since an EOA manager can simply disable the collateral via [this function](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AaveLeverageModule.sol#L1006-L1073). Once disabled it can never be triggered again. For set tokens utilizing baseManger they could simply transfer to an EOA, disable and transfer back to baseManager.

Hmm. How can the manager call this function? It‘s internal. As far as i can recall, it is only called on module removal and removeCollateral. Where the latter is not possible, as the token was never enabled as collateral in the module.

**Comment by IAm0x52** [comment]
Add then remove the collateral

**Comment by Shogoki** [comment]
> Add then remove the collateral

Ok, get the idea. 
However this should not work.
Because in addCollateral there is a call to validate, which checks the [ReserveConfigurationData](
https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AaveLeverageModule.sol#L1094)

specificially it checks for the `usageAsCollateralEnabled` [flag to be true](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AaveLeverageModule.sol#L1101), which, i think, is not the case for isolated Assets.

**Comment by IAm0x52** [comment]
![image](https://github.com/sherlock-audit/2023-05-Index-judging/assets/109287400/5b526232-cbfb-47d4-a25a-77e6ac283a40)

I've attached an image querying USDT on Polygon, which is an isolated collateral. As you can see, usageAsCollateralEnabled returns true.

Pool Data Provider:
https://polygonscan.com/address/0x69FA688f1Dc47d4B5d8029D5a35FB7a548310654#readContract 

USDT Contract address: 0xc2132D05D31c914a87C6611C10748AEb04B58e8F

**Comment by Shogoki** [comment]
Ah. Yes, you’re right. 
Sorry, my mistake, i was confusing sth. here… 
Agree that this fix would work. 

I do get your points, 
but i do still think this could be counted as a medium, similiar to rhe LTV=0 issue (#159)as someone from outside can block the core functionality, and operator intervention is needed to fix it.

**Comment by 0xffff11** [comment]
According to sherlocks rules a DoS were no funds are impacted but admins can take down the DoS in less than ~1year is a low. Also thanks to Lead Watsons feedback, I also tend more to a low because the likelihood is very low (Only can happen at the beginning + it is easy to get out from the DoS + no fonds are lost).

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with the Lead watson and Judge comments on this issue being low. 
Some of the key points:
- Only possible at the very beginning of a set token when the set has no other tokens or when there are temporarily no other aTokens (all SetTokens redeemed). 
- Either it can be redeployed or the DOS can be as mentioned [here](https://github.com/sherlock-audit/2023-05-Index-judging/issues/164#issuecomment-1636986517)
No loss of funds or impact significant enough for a medium.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Shogoki](https://github.com/sherlock-audit/2023-05-Index-judging/issues/164/#issuecomment-1610400613): rejected
