### ISSUE TITLE
Ruhum - AAVE v3 rewards are not integrated in ClaimModule

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#166]
Ruhum

high

# AAVE v3 rewards are not integrated in ClaimModule

## Summary
AAVE v3 has an active reward program where you earn tokens for supplying and borrowing funds: https://docs.aave.com/developers/whats-new/multiple-rewards-and-claim

It's not integrated, meaning a loss of funds for the protocol and its users.

## Vulnerability Detail
Each token & network has its own rewards. On Optimism, you earn OP tokens for example. Because the protocol has a significant amount of TVL, the rewards it earns could grow pretty quickly.

It already implements the necessary structure to collect rewards in the ClaimModule.

What's missing is an integration for AAVE v3. Here's the one for COMP for example: https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/integration/claim/CompClaimAdapter.sol

## Impact
Loss of rewards.

## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/ClaimModule.sol#L386

## Tool used

Manual Review

## Recommendation
Integrate the AAVE v3 rewards program.

**Comment by 0xruhum** [comment]
Escalate for 10 USDC

As stated, airdrops or rewards that are not claimed aren't valid issues **unless** they are part of the protocol design. Index has a ClaimModule that allows the manager to claim any rewards from the different protocol integrations. The issue describes how the current AAVE v3 integration doesn't support claiming the rewards through the module because of a missing adapter.

**Comment by IAm0x52** [comment]
Low. If set token ever needs to claim from AAVE V3 they would just add an AAV3 V3 adapter and claim the rewards. No rewards would be lost.

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
Agree with Lead Watson's comment. Failing to claim tokens that can be claimed does not mean the funds are lost.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xruhum](https://github.com/sherlock-audit/2023-05-Index-judging/issues/166/#issuecomment-1611911317): rejected
