### ISSUE TITLE
Ruhum - `withdrawEtherBalance()` will fail for MultiSig operator

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#168]
Ruhum

medium

# `withdrawEtherBalance()` will fail for MultiSig operator

## Summary
The operator is expected to be a MultiSig. The integration sends ETH to that address with a gas stipend of 2300 which won't be enough for the call to succeed.

## Vulnerability Detail
In `AaveLeverageStrategyExtension.withdrawEtherBalance()` the contract's ETH is sent to the operator address using the `transfer()` function:

```sol
    /**
     * OPERATOR ONLY: Withdraw entire balance of ETH in this contract to operator. Rebalance must not be in progress
     */
    function withdrawEtherBalance() external onlyOperator noRebalanceInProgress {
        msg.sender.transfer(address(this).balance);
    }
```

But, the operator address is expected to be a MultiSig: 0x6904110f17feD2162a11B5FA66B188d801443Ea4

At least, that's the case for the other modules, e.g.
- https://etherscan.io/address/0xb97f5a34696adf30db822612379235c3c53b714a#readContract#F10
- https://etherscan.io/address/0x0749ce17c983deb806d6b841c65b7359c3d5b104#readContract#F10

GnosisSafe proxies don't implement `receive()` but use `fallback()` which will use more than 2300 gas:

```sol
    fallback() external payable {
        // solhint-disable-next-line no-inline-assembly
        assembly {
            let _singleton := and(sload(0), 0xffffffffffffffffffffffffffffffffffffffff)
            // 0xa619486e == keccak("masterCopy()"). The value is right padded to 32-bytes with 0s
            if eq(calldataload(0), 0xa619486e00000000000000000000000000000000000000000000000000000000) {
                mstore(0, _singleton)
                return(0, 0x20)
            }
            calldatacopy(0, 0, calldatasize())
            let success := delegatecall(gas(), _singleton, 0, calldatasize(), 0, 0)
            returndatacopy(0, 0, returndatasize())
            if eq(success, 0) {
                revert(0, returndatasize())
            }
            return(0, returndatasize())
        }
    }
```

That will cause the transfer to fail.

## Impact
The module won't be able to use an operator that's a MultiSig. That will heavily reduce the security of the module since key functionality and configuration is handled by that address. It being a simple 1:1 hot wallet increases the risk of the module being compromised.

## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L584

## Tool used

Manual Review

## Recommendation
Use `call()` instead of `transfer()`. Since the address is trusted, there's no risk of reentrancy.

**Comment by 0xruhum** [comment]
Escalate for 10 USDC

This issue describes how the current setup will cause the admin to not be able to withdraw the ETH inside the contract. As described, the operator address will be a MultiSig that uses more than 2300 gas when receiving ETH. Because of that, the usage of `transfer()` will cause the tx to revert.

**Comment by 0xffff11** [comment]
2 things. Can you actually prove that the fallback from gnosis uses more than 2300 gas? That would be nice. Second, if the multisig can't withdraw, once they realize, coudln't they just create a multisig proposal to change the role owner to an EOA, withdraw, and change it back again. No funds are lost, right?

**Comment by hrishibhat** [comment]
Additionally @0xffff11 @0xruhum 
This should help
https://help.safe.global/en/articles/40813-why-can-t-i-transfer-eth-from-a-contract-into-a-safe
This can be considered a low issue.

**Comment by 0xffff11** [comment]
Yes, thanks hrishi! This should be a low, no funds are lost.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low
