### ISSUE TITLE
Auditwolf - Function repay reduces debt for the wrong address.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#174]
Auditwolf

high

# Function repay reduces debt for the wrong address.

## Vulnerability Detail

To get repay data this function calls getrepaycalldata function which defines Onbehalfof parameter as the Address of the user who will get his debt reduced/removed. Should be the address of the user calling the function if he wants to reduce/remove his own debt, or the address of any other borrower whose debt should be removed. In contrast , the address specified in the function invoke repay is to be always the msg.sender and not (_onbehalfof ) meaning the debt of the address (set token ) will always be reduced even though debt of another address was supposed to be reduced.

 
        ( , , bytes memory repayCalldata) = getRepayCalldata(
            _lendingPool,
            _asset,
            _amountNotional,
            _interestRateMode,
            address(_setToken)
        );
        

## Impact
users can't reduce debt for other borrowers even if they wanted to do so.

## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/integration/lib/AaveV3.sol#L305C1-L324C6

## Tool used

Manual Review

## Recommendation
Replace address(_setToken ) with address (_OnbehalfOf )

**Comment by htstarz** [comment]
Escalate for 10 usdc
Confirmed with the protocol team that when retrieving repay call data  it should be address (_Onbehalfof) being retrieved not the addres of the setToken. This also the case with functions invoke deposit and invoke borrow. issue ( #173, #118 )
