### ISSUE TITLE
0xGoodess - _repayBorrow would leave a residual allowance when the underlying debtToken is less than the _notionalQuantity

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#18]
0xGoodess

medium

# _repayBorrow would leave a residual allowance when the underlying debtToken is less than the _notionalQuantity

## Summary
_repayBorrow would leave a residual allowance when the underlying debtToken is less than the _notionalQuantity

## Vulnerability Detail
componentRedeemHook uses `_repayBorrowForHook` which calls `_repayBorrow`, In `_repayBorrow`, the function first approve the needed amount `notionalDebt` and then call repayBorrow in Aave which pull the amount. 

However, if the remaining debtTokenBalance is less than the approved amount, then aave would just pull the total of the debtToken:

1. SetToken has a debtToken of 10
2. SetToken call repayBorrow with amount 10.1
3. only 10 would be transferred to Aave, leaving 0.1 as a non-zero allowance.

```solidity
    function componentRedeemHook(ISetToken _setToken, uint256 _setTokenQuantity, IERC20 _component, bool _isEquity) external override onlyModule(_setToken) {
        // Check hook not being called for an equity position. If hook is called with equity position and outstanding borrow position
        // exists the loan would be paid down twice, decollateralizing the Set
        if (!_isEquity) {
            int256 componentDebt = _setToken.getExternalPositionRealUnit(address(_component), address(this));

            require(componentDebt < 0, "CMBN");

            uint256 notionalDebt = componentDebt.mul(-1).toUint256().preciseMulCeil(_setTokenQuantity);
            _repayBorrowForHook(_setToken, _component, notionalDebt);
        }
    }
```

```solidity
    function _repayBorrowForHook(ISetToken _setToken, IERC20 _asset, uint256 _notionalQuantity) internal {
        _repayBorrow(_setToken, IPool(lendingPoolAddressesProvider.getPool()), _asset, _notionalQuantity);
    }
```

```solidity
    function _repayBorrow(ISetToken _setToken, IPool _lendingPool, IERC20 _asset, uint256 _notionalQuantity) internal {
        _setToken.invokeApprove(address(_asset), address(_lendingPool), _notionalQuantity);
        _setToken.invokeRepay(_lendingPool, address(_asset), _notionalQuantity, BORROW_RATE_MODE);
    }
```
## Impact
leaving non-zero allowance in setToken.

## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L715-L726

## Tool used

Manual Review

## Recommendation
re-set the allowance to 0 at the end of each transaction that has called approve.

**Comment by chrisckwong821** [comment]
Escalate for 10 USDC
this is a duplicate of https://github.com/sherlock-audit/2023-05-Index-judging/issues/314

The explanation and reference is consistent with the residual allowance, and impact of the residual allowance is incompatibility to token like USDT.

**Comment by Shogoki** [comment]
Hey there, just my humble opinion on that. 
The report misses the impact that occurs from the leftover allowance. There is no word about tokens with approval race condition protection. 
The leftover allowance on its own is not enough for a valid Medium, i guess.

**Comment by 0xffff11** [comment]
Agree with @Shogoki In no place it is mentioned something about approval race/usdt. Low

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree that the impact `leaving non-zero allowance in setToken.` is not a valid medium

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [chrisckwong821](https://github.com/sherlock-audit/2023-05-Index-judging/issues/18/#issuecomment-1610888441): rejected
