### ISSUE TITLE
caventa - Wrapped ether's deposit and withdraw(uint) functions do not work in some chains

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#218]
caventa

medium

# Wrapped ether's deposit and withdraw(uint) functions do not work in some chains

## Summary
 Wrapped ether's deposit and withdraw(uint) functions do not work in some chains
 
## Vulnerability Detail
See Invoke.sol,

invokeWrapWETH function will call ```deposit()```
invokeUnwrapWETH function will call ```withdraw(uint256)```

Both function are used in WrapModuleV2#_validateUnwrapAndUpdate and WrapModuleV2#_validateWrapAndUpdate

See

```solidity
_setToken.invokeWrapWETH(address(weth), address(_setToken).balance);
_setToken.invokeUnwrapWETH(address(weth), notionalUnderlying);
```

For every WrapModuleV2 deployed, owner needs to specify weth

```solidity
    constructor(IController _controller, IWETH _weth) public ModuleBase(_controller) {
        weth = _weth;
    }
```

System assumes wrapped ether contract has ```deposit``` and ```withdraw(uint256)``` function. See IWETH interface

```solidity
interface IWETH is IERC20{
    function deposit()
        external
        payable;

    function withdraw(
        uint256 wad
    )
        external;
}
```

According to https://app.sherlock.xyz/audits/contests/81

Q: On what chains are the smart contracts going to be deployed?
**mainnet**, **Polygon**, **Optimism**, **Avalanche**, and **Arbitrum**

Below are the wrapped ether URLS for these 5 chains

- Etherscan https://etherscan.io/token/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2#code

- Polygon
https://polygonscan.com/token/0x7ceb23fd6bc0add59e62ac25578270cff1b9f619#code

- Optimism https://optimistic.etherscan.io/token/0x4200000000000000000000000000000000000006#code

- Avalanche
https://snowtrace.io/token/0x49d5c2bdffac6ce2bfdb6640f4f80f226bc10bab#code

- Arbitrum
https://arbiscan.io/token/0x82af49447d8a07e3bd95bd0d56f35241523fbab1#code (Proxy)
https://arbiscan.io/address/0x8b194beae1d3e0788a1a35173978001acdfba668#code (Implementation)

And all mentioned WETH **official website** is https://weth.io/

Ethereum, Optimism and Avalanche have deposit() function
Ethereum, Polygon, Optimism and Avalanche have withdraw(uint) function

Polygon and Avalanche do not have deposit() function
Avalanche does not have withdraw(uint) function

## Impact
Calling WrapModuleV2#WrapWithEther and WrapModuleV2#unwrapWithEther will always not work in some chains

## Code Snippet
https://github.com/IndexCoop/index-protocol/blob/master/contracts/protocol/modules/v1/WrapModuleV2.sol#L89
https://github.com/IndexCoop/index-protocol/blob/master/contracts/protocol/modules/v1/WrapModuleV2.sol#L424
https://github.com/IndexCoop/index-protocol/blob/master/contracts/protocol/modules/v1/WrapModuleV2.sol#L350

## Tool used
Manual Review

## Recommendation
For chains that do not support deposit or withdraw(uint) function, use another alternative functions that offer the same function

**Comment by jingyi2811** [comment]
Escalate for 10USDC
This should be considered valid.

**Comment by 0xffff11** [comment]
I agree, seems like a medium to me.

**Comment by IAm0x52** [comment]
Invalid. The "WETH" referenced in these contracts are the wrapped protocol tokens. WETH on ETH, WMATIC on Polygon, WAVAX on AVAX, etc.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Agree with the Lead Watson's comment. Considering this a non issue
