### ISSUE TITLE
rugpull_detector - PriceOracle.getPrice() will revert when inverse price is zero and there's no direct oracle but inverse, because of division by zero.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#238]
rugpull_detector

high

# PriceOracle.getPrice() will revert when inverse price is zero and there's no direct oracle but inverse, because of division by zero.

PriceOracle.getPrice() will revert when inverse price is zero and there's no direct oracle but inverse, because of division by zero.

## Summary
[PriceOracle.getPrice()#L126](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/PriceOracle.sol#L126) will always revert because of division by zero when there's no direct oracle and inverse oracle price is zero.

## Vulnerability Detail
- PriceOracle.getPrice() is very critical function of this system as it feeds important price information.
- It always call _getDirectOrInversePrice() first. _getDirectOrInversePrice checks if there's any direct oracle registered
- there's none then, it goes on to look for inverse oracle. 
- calculated price is PreciseUnitMath.preciseUnit() / Inverse oracle price is
- But if Inverse oracle read price is zero,  it reverts.

## Impact
There are several functions that rely on PriceOracle.getPrice()
- SetValuer.calculateSetTokenValuation()#L92 (https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/SetValuer.sol#L92)
- SetValuer.calculateSetTokenValuation()#L106 (https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/SetValuer.sol#L106)
- UniswapPairPriceAdapter.getPrice()#L138 (https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/integration/oracles/UniswapPairPriceAdapter.sol#L138)
- UniswapPairPriceAdapter.getPrice()#L145 (https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/integration/oracles/UniswapPairPriceAdapter.sol#L145)

## Code Snippets
PriceOracle.getPrice() https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/PriceOracle.sol#L117-L139
PriceOracle._getDirectOrInversePrice() https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/PriceOracle.sol#L253-L279
PriceOracle._calculateInversePrice() https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/PriceOracle.sol#L351-L356

## Tool used

Manual Review

## Recommendation
It should return false not revert when inverse oracle price indicates zero.

PriceOracle._calculateInversePrice()
```solidity
    function _calculateInversePrice(IOracle _inverseOracle) internal view returns(bool, uint256) {
        uint256 inverseValue = _inverseOracle.read();
+        if (inverseValue == 0)
+                return (false, 0);

-        return PreciseUnitMath.preciseUnit().preciseDiv(inverseValue);
+        return (true, PreciseUnitMath.preciseUnit().preciseDiv(inverseValue));
    }
```
PriceOracle._getDirectOrInversePrice()
```solidity
        // If not, check asset 2 -> asset 1. If exists, then return 1 / asset1 -> asset2
        if (hasInverseOracle) {
-                return (true, _calculateInversePrice(inverseOracle));
+                return calculateInversePrice(inverseOracle);
        }
```

**Comment by richardzheng29** [comment]
Escalate [10] for USDC

I think it's wrongly classified as duplicate.

Main point of this issue is that DOS by division by zero in case oracle price is zero and only reverse oracle is registered.

Regards.
rugpull_detector.

**Comment by richardzheng29** [comment]
Escalate for 10USDC

I think it's wrongly classified as duplicate.

Main point of this issue is that DOS by division by zero in case oracle price is zero and only reverse oracle is registered.

Regards.
rugpull_detector.

**Comment by 0xffff11** [comment]
If I am not wrong for this to happen it requires: `no direct oracle and inverse oracle price is zero.` Seems completely infesable to me. Also, what does it mean there is no direct oracle exactly?

**Comment by richardzheng29** [comment]
Given assetOne,assetTwo, direct oracle means oracles[_assetOne][_assetTwo], reverse oracle means [_assetTwo][_assetOne]

When oracles[_assetOne][_assetTwo] does not exist, but oracles[_assetTwo[_assetOne] exists, it uses reverse oracle price to calculate price by dividing with WAD.

But if reverse oracle price is zero, it gets reverted because of division by zero.

```solidity
    function _getDirectOrInversePrice(
        address _assetOne,
        address _assetTwo
    )
        internal
        view
        returns (bool, uint256)
    {
        IOracle directOracle = oracles[_assetOne][_assetTwo];
        bool hasDirectOracle = address(directOracle) != address(0);
```
```solidity
function _getDirectOrInversePrice(
        address _assetOne,
        address _assetTwo
    )
        internal
        view
        returns (bool, uint256)
    {
        IOracle directOracle = oracles[_assetOne][_assetTwo];
        bool hasDirectOracle = address(directOracle) != address(0);

        // Check asset1 -> asset 2. If exists, then return value
        if (hasDirectOracle) {
            return (true, directOracle.read());
        }

        IOracle inverseOracle = oracles[_assetTwo][_assetOne];
        bool hasInverseOracle = address(inverseOracle) != address(0);

        // If not, check asset 2 -> asset 1. If exists, then return 1 / asset1 -> asset2
        if (hasInverseOracle) {
            return (true, _calculateInversePrice(inverseOracle));
        }

        return (false, 0);
    }
```


PriceOracle.getPrice() https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/PriceOracle.sol#L117-L139
PriceOracle._getDirectOrInversePrice() https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/PriceOracle.sol#L253-L279
PriceOracle._calculateInversePrice() https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/PriceOracle.sol#L351-L356

**Comment by Evert0x** [comment]
Sounds like the scenario that will result in a DOS is very unlikely to happen, correct me if I'm wrong, but first it requires an admin action to include tokens with a incorrect oracle setup. Even if the price will hit 0 (which is very unlikely) it's unclear how long the DOS will take as the price can go up. The admin is also able to remove this token.

**Comment by richardzheng29** [comment]
Of course, probability of edge case situation might be low, but possbile. To prevent such sceanario, following fix might be safer for future.

```solidity
    function _calculateInversePrice(IOracle _inverseOracle) internal view returns(bool, uint256) {
        uint256 inverseValue = _inverseOracle.read();
+        if (inverseValue == 0)
+                return (false, 0);

-        return PreciseUnitMath.preciseUnit().preciseDiv(inverseValue);
+        return (true, PreciseUnitMath.preciseUnit().preciseDiv(inverseValue));
    }
PriceOracle._getDirectOrInversePrice()

        // If not, check asset 2 -> asset 1. If exists, then return 1 / asset1 -> asset2
        if (hasInverseOracle) {
-                return (true, _calculateInversePrice(inverseOracle));
+                return calculateInversePrice(inverseOracle);
        }
```

**Comment by hrishibhat** [comment]
Result:
Low
Unique
This issue is not a valid high/medium based on above comments:
https://github.com/sherlock-audit/2023-05-Index-judging/issues/238#issuecomment-1636729938

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [richardzheng29](https://github.com/sherlock-audit/2023-05-Index-judging/issues/238/#issuecomment-1610617130): rejected
