### ISSUE TITLE
0x52 - AaveV3LeverageModule component hooks contain broken logic that will result in dangerous borrowing/repaying

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#256]
0x52

high

# AaveV3LeverageModule component hooks contain broken logic that will result in dangerous borrowing/repaying

## Summary

When issuing or redeeming a set that deals with debt carrying instruments, the DebtIssuanceModuleV2 is expected to be used. This module contains call to component hooks in all of the modules associated with the set token. The hooks called within AaveV3LeverageModule are dangerous and will result in severe damage to the set.

## Vulnerability Detail

[DebtIssuanceModule.sol#L686-L696](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/DebtIssuanceModule.sol#L686-L696)

        address[] memory externalPositionModules = _setToken.getExternalPositionModules(address(_component));
        uint256 modulesLength = externalPositionModules.length;
        if (_isIssue) {
            for (uint256 i = 0; i < modulesLength; i++) {
                IModuleIssuanceHook(externalPositionModules[i]).componentIssueHook(_setToken, _setTokenQuantity, _component, _isEquity);
            }
        } else {
            for (uint256 i = 0; i < modulesLength; i++) {
                IModuleIssuanceHook(externalPositionModules[i]).componentRedeemHook(_setToken, _setTokenQuantity, _component, _isEquity);
            }
        }

When issuing and redeeming set tokens DebtIssuanceModuleV2 calls component hooks to adjust debt and equity positions. The problem is that the hooks in AaveV3LeverageModule are broken and perform incomplete and dangerous actions.

[AaveV3LeverageModule.sol#L786-L788](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L786-L788)

    function componentIssueHook(ISetToken _setToken, uint256 _setTokenQuantity, IERC20 _component, bool _isEquity) external override onlyModule(_setToken) {
        // Check hook not being called for an equity position. If hook is called with equity position and outstanding borrow position
        // exists the loan would be taken out twice potentially leading to liquidation
        if (!_isEquity) {
            int256 componentDebt = _setToken.getExternalPositionRealUnit(address(_component), address(this));

            require(componentDebt < 0, "CMBN");

            uint256 notionalDebt = componentDebt.mul(-1).toUint256().preciseMul(_setTokenQuantity);
            _borrowForHook(_setToken, _component, notionalDebt);
        }
    }

    function _borrowForHook(ISetToken _setToken, IERC20 _asset, uint256 _notionalQuantity) internal {
        _borrow(_setToken, IPool(lendingPoolAddressesProvider.getPool()), _asset, _notionalQuantity);
    }

We see above that when set tokens are issued, the module borrows tokens. The issue is that these tokens are not utilized in any way leading to borrowed tokens that remain in the contract without any use. This creates excess debt that would lead to the set token being liquidate and suffering a large loss.

## Impact

AaveV3LeverageModule component hooks will result in broken borrowing that will cause set token to be liquidated

## Code Snippet

[AaveV3LeverageModule.sol#L786-L788](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L786-L788)

## Tool used

Manual Review

## Recommendation

Rework issuance and redemption hooks to leverage and deleverage appropriately

**Comment by Jiaren-tang** [comment]
Escalate for 10 USDC. Would like to politely to ask to consider this issue as high severity

https://github.com/sherlock-audit/2023-05-Index-judging/issues/130

Consider another case, the market price just crash by 30% and the liquidation happens out side of the rebalance action

The duplicate 130 has a good description as well

> The issue can happen because there is no check to ensure that the notionalDebt amount does not decrease the health factor in Aave to near 1. If it is slightly above 1, a small change in price could trigger the liquidation of the leveraged position of the SetToken. This would result in a loss for the SetToken.

**Comment by Evert0x** [comment]
It seems to me that the Watson is describing the limits of the protocol in extreme market scenarios, I don't see a clear bug/flaw being described.

@0xffff11 what are your thoughts on the escalation?

**Comment by thangtranth** [comment]
Hi, in my issue #130, which is a duplicate of this one, the issue can happen in a normal volatile market. It does not need to be extreme scenario.

**Comment by ckoopmann** [comment]
Issuing new tokens should not increase the leverage ratio since the user provides aTokens in the required quantity for the tokens that are borrowed. I don't se anything in either this or the duplicate issue that contradicts that.
Maintaining the leverage ratio in case of price changes is the responsibility of the LeverageStrategyExtension.

**Comment by hrishibhat** [comment]
@thangtranth

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
Considering this issue a low based on the sponsor's comment above. 
https://github.com/sherlock-audit/2023-05-Index-judging/issues/256#issuecomment-1653661215

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ShadowForce](https://github.com/sherlock-audit/2023-05-Index-judging/issues/256/#issuecomment-1610159574): rejected
