### ISSUE TITLE
bulej93 - No way to withdraw ETH

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#257]
bulej93

high

# No way to withdraw ETH

## Summary
there is no mechaminism to withdraw any eth sent to the contract
## Vulnerability Detail
in `setToken.sol` there is a receive function that accepts any eth sent to the smart contract, however there is no  way that you can actually withdraw the eth.
## Impact
eth is stuck inside the contract forever
## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/SetToken.sol#L536
## Tool used

Manual Review

## Recommendation
have a withdraw function

**Comment by bulej93** [comment]
Escalate for 10 USDC .

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on Lead Watson comment
