### ISSUE TITLE
ShadowForce - users lose out on liquidity mining rewards

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#266]
ShadowForce

high

# users lose out on liquidity mining rewards

## Summary
users will lose out on AAVE liquidity mining rewards.
## Vulnerability Detail
there is a high likelyhood that AAVE v3 will enable mining rewards. This is a problem because currently the protocol has no way for a user to claim said rewards from AAVE v3.
we can observe below a tweet from aave stating they enabled liquidity mining on optimism and AAVE can launch more liquidity mining campagin
https://twitter.com/AaveAave/status/1555230478394966018?lang=en
these docs also detail how to implement said functions for reward claiming
https://docs.aave.com/developers/whats-new/multiple-rewards-and-claim
## Impact
users will not be able to claim rewards on AAVE when they should. This is a clear loss of reward and funds for the individual.
## Code Snippet
https://docs.aave.com/developers/whats-new/multiple-rewards-and-claim
https://github.com/IndexCoop/index-coop-smart-contracts/blob/317dfb677e9738fc990cf69d198358065e8cb595/contracts/adapters/AaveLeverageStrategyExtension.sol#L889
## Tool used

Manual Review

## Recommendation
we recommend the protocol adds a  function that allows user to claim rewards from liquidity 

Duplicate of #166

**Comment by Jiaren-tang** [comment]
Escalate for 10 USDC.

Want to politely ask for a medium, the protocol does lose liquidity mining rewards

**Comment by IAm0x52** [comment]
This and #166 are dupes

**Comment by hrishibhat** [comment]
Result:
Low
Duplicate of #166 
Agree with Lead Watson's comment [here](https://github.com/sherlock-audit/2023-05-Index-judging/issues/166#issuecomment-1622805442). Failing to claim tokens that can be claimed does not mean the funds are lost.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ShadowForce](https://github.com/sherlock-audit/2023-05-Index-judging/issues/266/#issuecomment-1610186885): rejected
