### ISSUE TITLE
ShadowForce - failure to handle erc 20 transfers

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#268]
ShadowForce

medium

# failure to handle erc 20 transfers

## Summary
erc 20 transfers are not handled
## Vulnerability Detail
```solidity
    function _resolveEquityPositions(
        ISetToken _setToken,
        uint256 _quantity,
        address _to,
        bool _isIssue,
        address[] memory _components,
        uint256[] memory _componentEquityQuantities,
        uint256 _initialSetSupply,
        uint256 _finalSetSupply
    )
        internal
    {
        for (uint256 i = 0; i < _components.length; i++) {
            address component = _components[i];
            uint256 componentQuantity = _componentEquityQuantities[i];
            if (componentQuantity > 0) {
                if (_isIssue) {
                    // Call SafeERC20#safeTransferFrom instead of ExplicitERC20#transferFrom
                    SafeERC20.safeTransferFrom(
                        IERC20(component),
                        msg.sender,
                        address(_setToken),
                        componentQuantity
                    );

                    IssuanceValidationUtils.validateCollateralizationPostTransferInPreHook(_setToken, component, _initialSetSupply, componentQuantity);

                    _executeExternalPositionHooks(_setToken, _quantity, IERC20(component), true, true);
                } else {
                    _executeExternalPositionHooks(_setToken, _quantity, IERC20(component), false, true);

                    // Call Invoke#invokeTransfer instead of Invoke#strictInvokeTransfer
                    _setToken.invokeTransfer(component, _to, componentQuantity);

                    IssuanceValidationUtils.validateCollateralizationPostTransferOut(_setToken, component, _finalSetSupply);
                }
            }
        }
    }
```
in the snippet above we see the function `_resolveEquityPositions` the problem here is that the function does not properly handle erc 20 transfers. This is evident when we take a look at this specific lines of code below.
```solidity
_setToken.invokeTransfer(component, _to, componentQuantity);
```
in the this snippet we can see the function does never handle the token return value. Therefore the function will not properly handle erc 20 transfers.
## Impact
Tokens that don't correctly implement the latest EIP20 spec, like USDT, will be unusable in the protocol as they revert the transaction because of the missing return value.
## Code Snippet
https://github.com/IndexCoop/index-coop-smart-contracts/blob/317dfb677e9738fc990cf69d198358065e8cb595/external/contracts/set/DebtIssuanceModuleV2.sol#L251-L289
## Tool used

Manual Review

## Recommendation
we recommend the protocol add logic to properly handle erc 20 transfers.

**Comment by Shogoki** [comment]
Escalate for 10USDC
I think this issue is not a duplicate of #314.
Moreover, i believe this should be invalid, because the stated impact is not correct.
invokeTransfer uses a low level call and returns the data, this is unchecked, which is an issue because of possible silent failures (see #169 ), but it will not revert as stated in the report.
Tokens not returning a bool is no problem, because the data is never tried to be parsed as bool, nor anything else.

**Comment by 0xffff11** [comment]
Most of the issues regarding broken erc20 implementations that include approvals, unchecked transfers etc. are mostly different mini issues in differents part of tbe code that all of them describe the same. Current implementation does not work with usdt and approvals are not done correctly. Can't open single issue for all of them.

**Comment by hrishibhat** [comment]
Result:
Invalid 
Unique 
Considering this a non-issue as mentioned in the escalation issue d oes not correctly identify the root cause.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Shogoki](https://github.com/sherlock-audit/2023-05-Index-judging/issues/268/#issuecomment-1611504306): accepted
