### ISSUE TITLE
ShadowForce - soiled assets will lead to a DOS in the lever function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#269]
ShadowForce

medium

# soiled assets will lead to a DOS in the lever function

## Summary
soiled assets will lead to a DOS in the lever function
## Vulnerability Detail
https://docs.aave.com/developers/whats-new/siloed-borrowing
> This feature allow assets with potentially manipulatable oracles (for example illiquid Uni V3 pairs) to be listed on Aave as single borrow asset. This means that if an asset is configured as siloed, it can't be borrowed in a position at the same time as with other assets. This helps mitigating the risk associated with such assets from impacting the overall solvency of the protocol. This condition can be found in the codebase here.

the quote is from the link above. As we can see an admin from aave can decide if an asset is soiled, and this is a problem because the protocol does not account for this fact.

1. suppose there are three collateral asset,
2. asset A and asset B and asset C
3. suddenly asset B is listed as a soiled asset by AAVE admin
4. all lever function would revert

```solidity
function lever(
        ISetToken _setToken,
        IERC20 _borrowAsset,
        IERC20 _collateralAsset,
        uint256 _borrowQuantityUnits,
        uint256 _minReceiveQuantityUnits,
        string memory _tradeAdapterName, // exchange name
        bytes memory _tradeData
    )
        external
        nonReentrant
        onlyManagerAndValidSet(_setToken)
    {
        // For levering up, send quantity is derived from borrow asset and receive quantity is derived from 
        // collateral asset
        ActionInfo memory leverInfo = _createAndValidateActionInfo(
            _setToken,
            _borrowAsset,
            _collateralAsset,
            _borrowQuantityUnits,
            _minReceiveQuantityUnits,
            _tradeAdapterName,
            true
        );

        // @audit
        _borrow(leverInfo.setToken, leverInfo.lendingPool, leverInfo.borrowAsset, leverInfo.notionalSendQuantity);

        uint256 postTradeReceiveQuantity = _executeTrade(leverInfo, _borrowAsset, _collateralAsset, _tradeData);

        uint256 protocolFee = _accrueProtocolFee(_setToken, _collateralAsset, postTradeReceiveQuantity);

        uint256 postTradeCollateralQuantity = postTradeReceiveQuantity.sub(protocolFee);

        _deposit(leverInfo.setToken, leverInfo.lendingPool, _collateralAsset, postTradeCollateralQuantity);

        _updateLeverPositions(leverInfo, _borrowAsset);

        emit LeverageIncreased(
            _setToken,
            _borrowAsset,
            _collateralAsset,
            leverInfo.exchangeAdapter,
            leverInfo.notionalSendQuantity,
            postTradeCollateralQuantity,
            protocolFee
        );
    }
```
because the function `lever` must first borrow, if it has a soiled asset, the function will always revert
## Impact
because a user has a soiled asset, they cannot call the lever function. Being unable to call this function when market is favorable for user will lose him out on potential gains if he were to have levered up. This is a loss of funds for the user
## Code Snippet
https://github.com/IndexCoop/index-coop-smart-contracts/blob/317dfb677e9738fc990cf69d198358065e8cb595/external/contracts/set/AaveLeverageModule.sol#L249-L295
## Tool used

Manual Review

## Recommendation
we recommend the project account for the potential soiled assets

**Comment by Jiaren-tang** [comment]
Escalate for 10 USDC.

https://github.com/sherlock-audit/2023-05-Index-judging/issues/94 is the duplicate of this issue as well

and politely ask for a valid medium, "adding / removing / enabling soiled asset" is very equal to set borrow / supply cap by AAVE V3 admin

**Comment by 0xffff11** [comment]
I would like to know the likelihood of aave "adding / removing / enabling soiled asset". As it happened before? If so, seems like it could be a medium

**Comment by Jiaren-tang** [comment]
https://docs.aave.com/developers/whats-new/siloed-borrowing#is-any-asset-currently-siloed-in-aave-v3-market

> Currently there is no asset marked siloed in any of the V3 markets. Risk or Pool admins can set already listed assets as siloed if needed as per market conditions. This feature can be used for new asset listing which may have higher risk.

**Comment by 0xffff11** [comment]
As per your snipped seems that this has never happen and can only happen in new listings? If so, I agree with low

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
This can be considered an acceptable risk it can be equivalent external protocol integration pausing or emergency action which is acceptable.
