### ISSUE TITLE
ShadowForce - use of tx.origin will cause problems with optimism

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#272]
ShadowForce

medium

# use of tx.origin will cause problems with optimism

## Summary
the use of tx.origin is incorrect
## Vulnerability Detail
For `onlyEOA` , `tx.origin` is used to ensure that the caller is from an EOA and not a smart contract.

```solidity
  /**
     * Throws if caller is a contract, can be used to stop flash loan and sandwich attacks
     */
    modifier onlyEOA() {
        require(msg.sender == tx.origin, "Caller must be EOA Address");
        _;
    }
```

However, according to [EIP 3074](https://eips.ethereum.org/EIPS/eip-3074#abstract),

This EIP introduces two EVM instructions AUTH and AUTHCALL. The first sets a context variable authorized based on an ECDSA signature. The second sends a call as the authorized account. This essentially delegates control of the externally owned account (EOA) to a smart contract.

Therefore, using tx.origin to ensure msg.sender is an EOA will not hold true in the event EIP 3074 goes through.
## Impact
Using modifier `onlyEOA` to ensure calls are made only from EOA will not hold true in the event EIP 3074 goes through.
## Code Snippet
https://github.com/IndexCoop/index-coop-smart-contracts/blob/317dfb677e9738fc990cf69d198358065e8cb595/contracts/lib/BaseExtension.sol#L56-L62
## Tool used

Manual Review

## Recommendation
Recommend using OpenZepellin's isContract function (https://docs.openzeppelin.com/contracts/2.x/api/utils#Address-isContract-address-). Note that there are edge cases like contract in constructor that can bypass this and hence caution is required when using this.
```solidity
  /**
     * Throws if caller is a contract, can be used to stop flash loan and sandwich attacks
     */
    modifier onlyEOA() {
        require(isContract(msg.sender)) 
        _;
    }
```

**Comment by Nabeel-javaid** [comment]
Escalate for 10 USDC

IMO this is a valid medium and satisfy the Sherlock criteria for the medium:

"Medium: There is a viable scenario (even if unlikely) that could cause the protocol to enter a state where a material amount of funds can be lost. The attack path is possible with assumptions that either mimic on-chain conditions or reflect conditions that have a reasonable chance of becoming true in the future. The more expensive the attack is for an attacker, the less likely it will be included as a Medium (holding all other factors constant). The vulnerability must be something that is not considered an acceptable risk by a reasonable protocol team."

Even though not implemented yet, if so happens in the future, it will break the core modifier of the system. And that satisfy the requirement for the medium category. System should be designed in a way to be safe even when the contract is interacting with the system.

**Comment by 0xffff11** [comment]
Sorry, I asked sherlock first because I knew it was accepted first. 
The response was: "This can be a valid low, as the eip is not yet implemented"
And I asked because I also consider it a low but it was awarded before.

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
As mentioned in the Judging guide
> Issues that result out of a future integration/implementation that was not intended are not valid issues. 

Judging guidelines take precedence over historical decisions. 
Additionally, this rule was added after the above-mentioned issue from the other contest.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [BugBusters](https://github.com/sherlock-audit/2023-05-Index-judging/issues/272/#issuecomment-1610769232): rejected
