### ISSUE TITLE
caventa - Accrued fee does not work with high streamingFeePercentage or previous claim was too long

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#274]
caventa

high

# Accrued fee does not work with high streamingFeePercentage or previous claim was too long

## Summary
Accrued fee does not work with high streamingFeePercentage or previous claim was too long

[Note: I mark this as high severity because positionMultiplier is important as it is used to update all the positions in an efficient way]

## Vulnerability Detail
See SteamingFeeModule#initialize

```solidity
require(_settings.maxStreamingFeePercentage < PreciseUnitMath.preciseUnit(), "Max fee must be < 100%.");
require(_settings.streamingFeePercentage <= _settings.maxStreamingFeePercentage, "Fee must be <= max.");
```

maxStreamingFeePercentage can be any value that is < 1
streamingFeePercentage can be any value < maxStreamingFeePercentage
        

Fee is accrued in StreamingFeeModule#accrueFee

```solidity
function accrueFee(ISetToken _setToken) public nonReentrant onlyValidAndInitializedSet
    (_setToken) {
        uint256 managerFee;
        uint256 protocolFee;

        if (_streamingFeePercentage(_setToken) > 0) {
            uint256 inflationFeePercentage = _calculateStreamingFee(_setToken); // @audit

            // Calculate incentiveFee inflation
            uint256 feeQuantity = _calculateStreamingFeeInflation(_setToken, inflationFeePercentage); // @audit

            // Mint new Sets to manager and protocol
            (
                managerFee,
                protocolFee
            ) = _mintManagerAndProtocolFee(_setToken, feeQuantity);

            _editPositionMultiplier(_setToken, inflationFeePercentage);
        }

        feeStates[_setToken].lastStreamingFeeTimestamp = block.timestamp;

        emit FeeActualized(address(_setToken), managerFee, protocolFee);
    }
```

InflationFeePercentage is calculated in StreamingFeeModule#_calculateStreamingFee

```solidity
 function _calculateStreamingFee(ISetToken _setToken) internal view returns(uint256) {
        uint256 timeSinceLastFee = block.timestamp.sub(_lastStreamingFeeTimestamp(_setToken));

        // Streaming fee is streaming fee times years since last fee
        return timeSinceLastFee.mul(_streamingFeePercentage(_setToken)).div(ONE_YEAR_IN_SECONDS);
    }
```

And the value should not greater than 1_000_000_000_000_000_000 (Which is 1).

See this line of code

```solidity
uint256 b = PreciseUnitMath.preciseUnit().sub(_feePercentage);
```

in StreamingFeeModule#_calculateStreamingFeeInflation

```solidity
function _calculateStreamingFeeInflation(
        ISetToken _setToken,
        uint256 _feePercentage
    )
        internal
        view
        returns (uint256)
    {
        uint256 totalSupply = _setToken.totalSupply();

        // fee * totalSupply
        uint256 a = _feePercentage.mul(totalSupply);

        // ScaleFactor (10e18) - fee
        uint256 b = PreciseUnitMath.preciseUnit().sub(_feePercentage); // @audit

        return a.div(b);
    }
```    

If not, ```PreciseUnitMath.preciseUnit().sub(_feePercentage)``` will give subtraction overflow.

Sadly, this can happen with 

1) high streamingFeePercentage. 

block.timestamp = 1_718_289_524
lastStreamingFeeTimestamp = 1_686_731_919
timeSinceLastFee = 1_718_289_524 - 1_686_731_919 = 31_557_605 (After 1 year)
streamingFeePercentage = 999_999_990_000_000_000 (Which is 0.99999999)
one year in second = 31_557_600

Streaming fee 
= timeSinceLastFee * streamingFeePercentage / one year in second
= 1_000_000_148_440_437_485

which is more than 1_000_000_000_000_000_000 (1 * 10^18)

2) Previous claim was too long 

block.timestamp = 1_718_289_524
lastStreamingFeeTimestamp = 20_336_49_524
timeSinceLastFee = 20_336_49_524 - 1_718_289_524 =  315_360_000 (After 10 years)
streamingFeePercentage = 110_000_000_000_000_000 (Which is 0.11) [This time this value is small]
one year in second = 31_557_600

Streaming fee 
= timeSinceLastFee * streamingFeePercentage / one year in second
= 1_099_247_091_033_538_672

## Impact
Accrued fee will not work if streamingFeePercentage is too high or previous claim was too long.

## Code Snippet
https://github.com/IndexCoop/index-protocol/blob/master/contracts/protocol/modules/v1/StreamingFeeModule.sol#L224-L241
https://github.com/IndexCoop/index-protocol/blob/master/contracts/protocol/modules/v1/StreamingFeeModule.sol#L203-L208
https://github.com/IndexCoop/index-protocol/blob/master/contracts/protocol/modules/v1/StreamingFeeModule.sol#L86-L108C6
## Tool used

Manual Review
Manual and added hardhat test unit

## Recommendation
Don't allow high streamingFeePercentage value to be set. We cannot control how long people wait until the next claim. We can only control the value of streamingFeePercentage 

Duplicate of #147

**Comment by jingyi2811** [comment]
Escalate for 10USDC
This should be considered valid.

**Comment by 0xffff11** [comment]
See my comment in issue: https://github.com/sherlock-audit/2023-05-Index-judging/issues/147 as their are dups

**Comment by hrishibhat** [comment]
Result:
Low
Duplicate of #147 
Considering this issue low for reasons mentioned in #147
