### ISSUE TITLE
tsvetanovv - It's possible to withdraw the contract balance during rebalance period

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#282]
tsvetanovv

medium

# It's possible to withdraw the contract balance during rebalance period

## Summary
In `AaveLeverageStrategyExtension.sol` we have `withdrawEtherBalance()` function:
```solidity
/**
     * OPERATOR ONLY: Withdraw entire balance of ETH in this contract to operator. Rebalance must not be in progress
     */
    function withdrawEtherBalance() external onlyOperator noRebalanceInProgress {
        msg.sender.transfer(address(this).balance);
    }
```
 This function withdraws the entire balance of ETH in this contract to the operator. 
 - *Rebalance must not be in progress*
 
## Vulnerability Detail

But there is a way to pull the balance out of the contract and get around `noRebalanceInProgress()`.

- A user can call the `ripcord()` function to get rewards in ETH
- `ripcord()` call `_transferEtherRewardToCaller()` function
- If the ETH balance on this contract is less than the required incentive quantity, then transfer the contract balance instead to prevent reverts

In this situation, ETH can be withdrawn from the contract during the rebalancing period.

## Impact

`noRebalanceInProgress()` modifier can be bypassed and ETH balance can be withdrawn during the rebalance period

## Code Snippet

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L580-L585
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L1218-L1224

## Tool used

Manual Review

## Recommendation

Add `noRebalanceInProgress()` modifier to `_transferEtherRewardToCaller()`

**Comment by cvetanovv** [comment]
Escalate for 10 USDC

Here I have explained how you can `Withdraw entire balance of ETH in this contract.... Rebalance must not be in progress`, during rebalance

**Comment by 0xffff11** [comment]
Isn't the operator the only one that can do this? If so, I do not see the issue here because they are trusted.

**Comment by cvetanovv** [comment]
Anyone can do this. ripcord() is public function that anyone can call.

**Comment by Evert0x** [comment]
It seems to me that the intention of the comment to describe the way the function behaves, it's not describing a protocol wide design rule that no ETH can ever be withdrawn in case the protocol is in a re-balancing period.

@0xffff11 what's you take on this?

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with Evert's comment. Not a valid high/medium

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [cvetanovv](https://github.com/sherlock-audit/2023-05-Index-judging/issues/282/#issuecomment-1610803393): rejected
