### ISSUE TITLE
0x52 - AaveLeverageStrategyExtension and underlying AaveV3 oracles may diverge

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#284]
0x52

medium

# AaveLeverageStrategyExtension and underlying AaveV3 oracles may diverge

## Summary

Both AaveLeverageStrategyExtension and the underlying AaveV3 protocol utilize oracles. AaveLeverageStrategyExtension uses an (effectively) immutable oracle while AaveV3 uses it's in-house AaveOracle. While both are initially use Chainlink, the AaveV3 oracle is mutable and can be changed at a later time. This allows divergence between the two oracles and therefore a difference in decision making based on those differences. Since AaveV3 is the underlying protocol that enforces liquidation it is extremely important that the extension uses the same oracle at all times.

## Vulnerability Detail

See summary.

## Impact

Divergence in oracle data may lead to a host of issues including liquidation, especially due to the leverage nature of the contracts

## Code Snippet

[AaveLeverageStrategyExtension.sol#L889-L907](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L889-L907)

## Tool used

Manual Review

## Recommendation

Utilize AaveOracle rather than setting a different one

Duplicate of #323

**Comment by IAm0x52** [comment]
Escalate for 10 USDC

I realize this is an edge case but still something to consider. Oracle should always be EXACTLY aligned with the underlying protocol and any divergence can cause serious issues like liquidation. This is much more concerning for high leverage scenarios where small difference can make very large differences.

**Comment by 0xffff11** [comment]
I definitely see the point. According to the issue, currently I see no issue here as both use chainlink. I see that as you pointed out aaves oracle can change because it is mutable. I think relaying on the fact that aave can change oracles due to being mutable is low. The decision of aave to change the oracle are completely external.  
A comparison for me to bring it to low is that uniswap can enable fees whenever they want to. This would break a lot of protocols. Issue is still low. Same here.

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #323 
Considering this a valid issue. 
https://github.com/sherlock-audit/2023-05-Index-judging/issues/323#issuecomment-1658325941

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [IAm0x52](https://github.com/sherlock-audit/2023-05-Index-judging/issues/284/#issuecomment-1612159709): accepted
