### ISSUE TITLE
tsvetanovv - Don't rely on just one `module` to unlock the `SetToken.sol` contract

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#286]
tsvetanovv

medium

# Don't rely on just one `module` to unlock the `SetToken.sol` contract

## Summary
In `SetToken.sol` we have `lock()` and `unlock()` functions:

```solidity
function lock() external onlyModule { 
        require(!isLocked, "Must not be locked");
        locker = msg.sender;
        isLocked = true;
    }

function unlock() external onlyModule {
        require(isLocked, "Must be locked");
        require(locker == msg.sender, "Must be locker");
        delete locker;
        isLocked = false;
    }
```

The `lock` and `unlock` functions here are used to control access to certain functionalities of the SetToken contract. Only approved modules can call these functions due to the `onlyModule` modifier.

Modules can only be added from the manager by `addModule()` or in the constructor.
```solidity
function addModule(address _module) external onlyManager {
        require(moduleStates[_module] == ISetToken.ModuleState.NONE, "Module must not be added");
        require(controller.isModule(_module), "Must be enabled on Controller");
  
        moduleStates[_module] = ISetToken.ModuleState.PENDING; 

        emit ModuleAdded(_module);
    }
```

## Vulnerability Detail

Don't rely on just one `module` to unlock the `SetToken.sol` contract. If one module use `lock()` only the same module can call `unlock()`. 
Imagine the situation one module is hacked or becomes malicious or due to a bug, he can lock the most function in the contract.

Even the Manager cannot remove it via `removeModule()` becouse the contract need to be unlocked:

```solidity
function removeModule(address _module) external onlyManager {
        require(!isLocked, "Only when unlocked");
        require(moduleStates[_module] == ISetToken.ModuleState.INITIALIZED, "Module must be added");

        IModule(_module).removeModule();

        moduleStates[_module] = ISetToken.ModuleState.NONE;
  
        modules.removeStorage(_module);

        emit ModuleRemoved(_module);
    }
```
## Impact

If a module that has locked the contract becomes unable to call the unlock function due to a bug, is hacked, or becomes malicious it could lead to a situation where the contract remains locked indefinitely, which can effectively freeze significant parts of the contract's operations.

## Code Snippet

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/SetToken.sol#L343-L387

## Tool used

Manual Review

## Recommendation

Implementing a fail-safe mechanism where a trusted party, has the ability to unlock the contract in case of such a situation.
As an example you can add that `unlock()` can call it and a manager besides `locker`.

**Comment by cvetanovv** [comment]
Escalate for 10 USDC

I've explained how dangerous it is to rely on just one module to unlock the contract.
You can see a similar report from a previous contest: https://github.com/sherlock-audit/2023-02-telcoin-judging/issues/67

**Comment by 0xffff11** [comment]
Invalid. As you said, for this to happen,  the module contract should be hacked first. If you can't tell me how would that happen, then the issue should be invalid.

**Comment by cvetanovv** [comment]
Now I looked at the escalations again and I think this report can be grouped with #107 and #131

**Comment by Evert0x** [comment]
The difference between the mentioned issue in the Telcoin codebase is that Telcoin didn't have any plugins in scope. In this codebase the plugins are in scope. With those in-scope plugins (and trusted admins) this issue doesn't seem valid to me.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
In addition to Evert's comment above,
Set-Token manager is trusted to manage modules on the SetToken

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [cvetanovv](https://github.com/sherlock-audit/2023-05-Index-judging/issues/286/#issuecomment-1610794476): rejected
