### ISSUE TITLE
BugBusters - Emode cannot be enable on Aave Leverage Extension due to call to wrong function.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#295]
BugBusters

high

# Emode cannot be enable on Aave Leverage Extension due to call to wrong function.

## Summary
Calling the function with wrong signature in extension, never enables the e-mode and instead reverts.
## Vulnerability Detail
One of the new feature added to the codebase is the use of the Aave V3 E-mode, which give more capital efficiency and high borrowing power of upto 97%.
```solidity
    function setEModeCategory(uint8 _categoryId) external onlyOperator {
        _setEModeCategory(_categoryId);
    }

    function _setEModeCategory(uint8 _categoryId) internal {
        bytes memory setEmodeCallData =
            abi.encodeWithSignature("setEModeCategory(address,uint8)", address(strategy.setToken), _categoryId);
        invokeManager(address(strategy.leverageModule), setEmodeCallData);
    }
```
But the leverage extension is calling the function with signature `setEModeCategory(address,uint8)` which is the admin specific function and cannot be called by anyone, only risk admin and pool admin can call this function as per the docs here:
https://docs.aave.com/developers/core-contracts/poolconfigurator#setsiloedborrowing
```text
setEModeCategory (categoryId, ltv, liquidationThreshold, liquidationBonus, oracle, label)
And the function used to enable the e-mode in extension is calling the wrong function which is only callable by risk admin of the pool.
```

The right function to be called is `setUserEmode` that enables the E-mode for the sender, which is the desired move for the protocol.
## Impact
E-mode cannot be enabled.
## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-coop-smart-contracts/contracts/adapters/AaveV3LeverageStrategyExtension.sol#L60-L68
## Tool used

Manual Review

## Recommendation
User the right function of `setUserEmode`

**Comment by Shogoki** [comment]
Escalate for 10USDC 
This issue is no duplicate of #251 and is invalid. 
The function signature, that is mentioned in the issue is not the one that is called on the AAVE contract, but on the `leverageModule`.
And it has the correct function with this signature:
https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L566

**Comment by 0xffff11** [comment]
Seems like the watson that submitted the issue made a mistake by confusing implementation contracts. Agree with non duplication + invalid if no extra info is given

**Comment by hrishibhat** [comment]
Result: 
Invalid
Unique 
Considering this a non issue based on the escalation and the comment
