### ISSUE TITLE
Angry_Mustache_Man - Index is vulnerable to attackers sending LTV = 0 collateral tokens, supply/supplyCollateral, borrow and liquidate operations could stop working

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#303]
Angry_Mustache_Man

high

# Index is vulnerable to attackers sending LTV = 0 collateral tokens, supply/supplyCollateral, borrow and liquidate operations could stop working

## Summary
When an AToken has LTV = 0, Aave restricts the usage of some operations which could affect the Index protocol critically.
## Vulnerability Detail
When an AToken has LTV = 0, Aave restricts the usage of some operations. In particular, if the user
owns at least one AToken as collateral that has LTV = 0, these operations could revert
1) Withdraw: if the asset withdrawn is collateral, the user is borrowing something, the operation will revert if the
withdrawn collateral is an AToken with LTV > 0.
2) Transfer: if the from is using the asset as collateral, is borrowing something and the asset transferred is an
AToken with LTV > 0 the operation will revert.
3) Set the reserve of an AToken as not collateral: if the AToken you are trying to set as non-collateral is an
AToken with LTV > 0 the operation will revert.

Note that as `invokeWithdraw` and `invokeBorrow` is external ,  this attack is completely possible. In the attack scenario, the bad actor could simply supply an underlying that is associated with an LTV = 0 AToken and transfer it to the Index contract. If the victim does not own any balance of the asset, it will be set as collateral and the victim will suffer from all the side effects previously explained.
## Impact
 Impact would be - if the user
owns at least one AToken as collateral that has LTV = 0, these operations could revert
1) Withdraw: if the asset withdrawn is collateral, the user is borrowing something, the operation will revert if the
withdrawn collateral is an AToken with LTV > 0.
2) Transfer: if the from is using the asset as collateral, is borrowing something and the asset transferred is an
AToken with LTV > 0 the operation will revert.
3) Set the reserve of an AToken as not collateral: if the AToken you are trying to set as non-collateral is an
AToken with LTV > 0 the operation will revert.
## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/integration/lib/AaveV3.sol#L154

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/integration/lib/AaveV3.sol#L230

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/integration/lib/AaveV3.sol#L154

## Tool used

Manual Review

## Recommendation
One possible solution that Index could explore after elaborating all the pros/cons/side effects and possible problems could be to allow a DAO to set the "poison asset" as non-collateral. If the asset is part of Index's markets, they must be sure that Index's Aave position remains healthy. If the asset is not part of Index's markets, there should be no problem regarding the health factor.

**Comment by 0xffff11** [comment]
Thanks for escalating it and bringing this out. Indeed seems that you are right and watsons submitted without understanding. Invalid given the good arguments in the escalation.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
This issue does not identify the original issue as identified in #315 & #159. 
This issue incorrectly applies the logic of one protocol to another without clearly identifying the issue. 
https://github.com/sherlock-audit/2023-05-Index-judging/issues/159#issuecomment-1600056175

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [hildingr](https://github.com/sherlock-audit/2023-05-Index-judging/issues/303/#issuecomment-1613533775): accepted
