### ISSUE TITLE
Cryptor - RemoveModule in AMM module does not check if there is outstanding liquidity in an AMM

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#44]
Cryptor

high

# RemoveModule in AMM module does not check if there is outstanding liquidity in an AMM

## Summary
The function remove module in AMMmodule.sol. removes a module from the protocol. However, the module involves investing user funds in AMM pools, and with no check to make sure that all liquidity has been removed. 

## Vulnerability Detail

The function remove module removes a module from the protocol. However, the module has several functions that allows the manager to add and remove liquidity to AMM pools shown here.

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AmmModule.sol#L108-L118

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AmmModule.sol#L206-L213

However, the function removeModule does not remove liquidity. 

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AmmModule.sol#L310

So there could be a situation where liquidity is added and then Removemodule is called leaving funds stranded in various AMM protocols. This could be a problem when interacting with a protocol like uniswap where after adding liquidity, a settoken contract is given an NFT as a representation of the LP position. If removemodule is called and a user tries to redeem tokens, then there may be an accounting error where users are receiving less collateral than they should receive. This is because the protocol is not designed to handle NFTs

## Impact

Accounting error when removemodule is called due to not being able to handle LP NFTs left in the contract

## Code Snippet

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AmmModule.sol#L310

## Tool used

Manual Review

## Recommendation

Add check to make sure that all liquidity is removed before removing a module when using an AMM module

**Comment by JJtheAndroid** [comment]
Escalate for 10 USDC

I believe that this issue should be valid. The contest readme states that this protocol does not expect to receive ERC721 tokens 

<img width="476" alt="image" src="https://github.com/sherlock-audit/2023-05-Index-judging/assets/29849840/a19eb937-e50e-4e2f-bd59-8cf5fbe1a1dd">

Yet this is exactly what will happen if the an AMM module adds liquidity in a protocol like Uniswap. The set token contract will receive an ERC721 token. As explained in the report, this can result in users not being able to withdraw the correct amount of funds if remove module is called and there is an ERC721 LP token in the contract. In addition the remove module functions in other modules such as the Aave leverage module are not empty. So there is no expectation for the manager to know whether he has an outstanding position in a module.

**Comment by 0xffff11** [comment]
"where liquidity is added and then Removemodule is called" do you mean in the same transaction?

**Comment by JJtheAndroid** [comment]
Not necessarily. The issue is present either in the same transaction or a separate one

**Comment by Evert0x** [comment]
@0xffff11 any thoughts on this last message?

**Comment by JJtheAndroid** [comment]
For my final point, the uniswap V3 license has expired recently, so there will many more forks of this protocol where the same issue will be present

**Comment by ckoopmann** [comment]
Description and comments seem factually correct. Indeed the contract receives ERC721 LP positions when providing liquidity, which should have been mentioned in the linked part of the audit scope / description.

Generally this issue seems to rely on operator error though. Also it can be remediated by adding the module back, so this does not seem any fix on our side. 

Will defer to the watsons / judges regarding validity / severity.

**Comment by JJtheAndroid** [comment]
I will reiterate a previous point which is that the protocol makes no assumption that the operator knows whether he/she has an outstanding position. The same removemodule function is not empty in the Aave leverage module https://github.com/sherlock-audit/2023-05-Index-JJtheAndroid/blob/df49abd057b336acbbf835fb73128d35dbba8ac9/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L514

or in the compoundleveragemodule 
https://github.com/sherlock-audit/2023-05-Index-JJtheAndroid/blob/df49abd057b336acbbf835fb73128d35dbba8ac9/index-protocol/contracts/protocol/modules/v1/CompoundLeverageModule.sol#L471.

 It is pretty bizarre to assume that the operator is suddenly smart enough to remember all of his/her AMM positions.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
As pointed out by the Sponsor this requires Operator error for the issue to cause damage and the for removing a module which can be rare action, the admin must make sure to communicate accordingly

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [JJtheAndroid](https://github.com/sherlock-audit/2023-05-Index-judging/issues/44/#issuecomment-1610231114): rejected
