### ISSUE TITLE
saidam017 - `validateCollateralizationPostTransferInPreHook` could not work with token that have fee on transfer

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#51]
saidam017

medium

# `validateCollateralizationPostTransferInPreHook` could not work with token that have fee on transfer

## Summary

`validateCollateralizationPostTransferInPreHook()` used inside `DebtIssuanceModuleV2` to verify the transferred token is at least (position unit of the component x initial supply) + amount transferred. However, if token with fee on transfer is used, the received value for set token is less than the actual amount, and make the call mistakenly revert.

## Vulnerability Detail

`validateCollateralizationPostTransferInPreHook()` is used to verify that `_initialSetSupply.preciseMulCeil(defaultPositionUnit).add(_componentQuantity)`  is at least equal `newComponentBalance` : 

```solidity
  function validateCollateralizationPostTransferInPreHook(
    ISetToken _setToken,
    address _component,
    uint256 _initialSetSupply,
    uint256 _componentQuantity
  ) internal view {
    uint256 newComponentBalance = IERC20(_component).balanceOf(address(_setToken));

    uint256 defaultPositionUnit = _setToken
      .getDefaultPositionRealUnit(address(_component))
      .toUint256();
    // @audit - this not work for fee on transfer
    require(
      newComponentBalance >=
        _initialSetSupply.preciseMulCeil(defaultPositionUnit).add(_componentQuantity),
      "Invalid transfer in. Results in undercollateralization"
    );
  }
```

` newComponentBalance` is calculated from current balance of set token and will always increase less than the `_componentQuantity` if fee on transfer token is used.

## Impact

The hook could revert and make the `DebtIssuanceModuleV2` not support tokens with fee on transfer.

## Code Snippet

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/lib/IssuanceValidationUtils.sol#L61-L65

## Tool used

Manual Review

## Recommendation

Calculate the initial set token's component balance before transfer : 

```solidity
          ....
          // get the initial balance before transfer
         uint256 _initialBalance = IERC20(component).balanceOf(address(_setToken));

          // Call SafeERC20#safeTransferFrom instead of ExplicitERC20#transferFrom
          SafeERC20.safeTransferFrom(
            IERC20(component),
            msg.sender,
            address(_setToken),
            componentQuantity
          );

          IssuanceValidationUtils.validateCollateralizationPostTransferInPreHook(
            _setToken,
            component,
            _initialSetSupply,
            _initialBalance, // New param, pass it to the hook
          );
         ....
```

Pass it to ` validateCollateralizationPostTransferInPreHook()` to check it using the balance change instead of `_componentQuantity`. :  

```solidity
  function validateCollateralizationPostTransferInPreHook(
    ISetToken _setToken,
    address _component,
    uint256 _initialSetSupply,
    uint256 _initialBalance
  ) internal view {
    uint256 newComponentBalance = IERC20(_component).balanceOf(address(_setToken));
    uint256 defaultPositionUnit = _setToken
      .getDefaultPositionRealUnit(address(_component))
      .toUint256();
    // @audit - this not work for fee on transfer
    require(
      // Use preciseMulCeil to increase the lower bound and maintain over-collateralization
      newComponentBalance >=
        _initialSetSupply.preciseMulCeil(defaultPositionUnit).add(_initialBalance.sub(newComponentBalance)),
      "Invalid transfer in. Results in undercollateralization"
    );
  }
```

**Comment by said017** [comment]
Escalated for 10 USDC

The reason I report this issue because it is mentioned on sherlock page, even until now the statement is still the same :

![image](https://github.com/sherlock-audit/2023-05-Index-judging/assets/19762585/7c522ed0-5862-4161-abcd-7af3526b097d)

This should be valid issue.

**Comment by stalinMacias** [comment]
From a response I got on one of my findings [#61](https://github.com/sherlock-audit/2023-05-Index-judging/issues/61#issuecomment-1607212842)
`
Might have been an unclear statement on the docs. Index does not try to support fee-on-transfer tokens. Invalid

`

**Comment by said017** [comment]
thanks sir for the information @stalinMacias . According to https://docs.sherlock.xyz/audits/judging/judging, README is at the top of hierarchy of truth :

![image](https://github.com/sherlock-audit/2023-05-Index-judging/assets/19762585/6499a454-69ec-403b-a92b-c72f74f833aa)

It feels unfair to get penalty due to mistakes on the README statement.

**Comment by stalinMacias** [comment]
I think you have a point here @said017 .
Let's see how it plays out on the escalation phase, I'm also thinking of escalating my finding, I didn't know about this **hierarchy of truth* and it seems that what's on the README it is the criteria that should be used to assess the findings.

**Comment by chainNue** [comment]
Looking at  
>"Not at the moment, but it would be good to know if they can interact with our smart contracts", 

IMO, it is emphasise on `not at the moment`, and the `but it would be good to know` sounds like they're accepting suggestion/info, so not a mandatory, thus, it might be considered as a low. Not sure how judge will see this.

**Comment by said017** [comment]
`not at the moment` suggests potential future interaction, and this issue shows that the interaction will not work properly. However, it is up to the sponsor to change their mind and say they won't support FoT at all. But changing their statement in the middle of the contest without updating README might seems not to be the best action, might need a better way to handle this kind of situation in the future.

**Comment by chainNue** [comment]
according to https://docs.sherlock.xyz/audits/judging/judging
> Future issues: Issues that result out of a future integration/implementation that was not intended (mentioned in the docs/README) or because of a future change in the code (as a fix to another issue) are not valid issues.

totally agree on README should be "frozen" and not accepting terms/updates on discord.

**Comment by said017** [comment]
> Future issues: Issues that result out of a future integration/implementation that was not intended (**mentioned in the docs/README**) or because of a future change in the code (as a fix to another issue) are not valid issues.

But it is mentioned on the docs/README.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
While the statement in the readme can be open to interpretations, it clearly mentions that the code is not designed to support Fee-On-Transfer tokens in its current state.
Considering this a low issue.
