### ISSUE TITLE
0xGoodess - protocol would fails to delever without flashloan when the collateral value falls short of the LTV requirement

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#7]
0xGoodess

high

# protocol would fails to delever without flashloan when the collateral value falls short of the LTV requirement

## Summary
protocol would fails to delever without flashloan when the collateral value falls short of the LTV requirement

## Vulnerability Detail
With reference to [ETH Strat](https://indexcoop.com/products/interest-compounding-eth-index), consider a case of ETH strategy of -175% ETH + 275% stETH with targeted 2.75 leverage. The aave-v3 LTV of wstETH is 68.5%, and liquidation threshold is 79.5% with [eMode disabled](https://app.aave.com/reserve-overview/?underlyingAsset=0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0&marketName=proto_mainnet_v3). 

When stETH is fully pegged to ETH, then the protocol has a health factor of 275 * 0.795 / 175 = 1.249.

When stETH depegs, leading to an increase in leverage, the protocol needs to sell off stETH to bring down the leverage; However since the LTV of stETH is only 68.5%, that means stETH cannot be withdrawn, when stETH price drops to 0.929. 
(The maths comes in this way: 275 * 0.929 => 175) When `collateral * LTV <= borrowed asset`, withdrawal of collateral is disabled in aave. (health factor is still above 1 so the position is free from liquidation.)

Normal withdrawal path would not be possible due to collateral value falls under LTV requirement now

In this scenario, the protocol can only delever through the use of flashloan:
1. Flashloan some ETH, deposit in the position to increase the LTV
2. withdraw the required amount of wstETH, sell-off to ETH.
3. Withdraw the difference in ETH needed, return the flashloan plus flashloan premium.

## Impact
protocol would fails to delever without flashloan when the withdrawal amount exceeds the LTV requirement

## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L775-L797

## Tool used

Manual Review

## Recommendation
Consider add a delever path that uses flashloan when the traditional withdrawal fails.

**Comment by chrisckwong821** [comment]
Escalate for 10 USDC

The index protocol is designed in such a way that a single withdrawal cannot be bigger than the withdrawable from Aave(determined by LTV).

With the targeted leverage of 2.75, and LTV 68.5% for wstETH; there is a non-negligible chance that the protocol falls into a state that withdrawable from Aave is "0", when wstETH quickly depegs even before anyone withdraws, or the protocol manages to cut leverage. In such a scenario, the protocol is "stuck" since no withdrawal or deleverage becomes possible.

Deleverage requires first : withdraw wstETH, sell to ETH and then repay ETH. With no withdrawable the first step would fail.


Unless the protocol team deems there is no chance that the protocol would get into this state, deleveraging with flashloan is a needed feature, or the protocol has a chance to get into an unsalvageable state.

**Comment by IAm0x52** [comment]
Dupe of #255

See sponsor comments as to why this is invalid

**Comment by hrishibhat** [comment]
@chrisckwong821 
this is the Sponsor comment from #255 
> It seems that the above issue is based on the assumption that one cannot withdraw  from aave if the withdrawal would cause the LTV to exceed the max LTV.
> However based on the [documentation](https://docs.aave.com/developers/core-contracts/pool#withdraw): _"the max amount available to withdraw is the amount that will not leave user health factor < 1 after withdrawal".

> Based on [the definition of the health factor](https://docs.aave.com/risk/asset-risk/risk-parameters#health-factor), it follows that using the liquidationThreshold is in fact correct, rendering this issue invalid. 

Let us know if you have any additional comments

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on Sponsor comment quoted above.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [chrisckwong821](https://github.com/sherlock-audit/2023-05-Index-judging/issues/7/#issuecomment-1612594996): rejected
