### ISSUE TITLE
rvierdiiev - Operator will not be able to call withdrawEtherBalance after disengage call, when twapLeverageRatio is not 0

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#71]
rvierdiiev

medium

# Operator will not be able to call withdrawEtherBalance after disengage call, when twapLeverageRatio is not 0

## Summary
In case if `twapLeverageRatio != 0` and operator will call `disengage` in order to make full deleverage, then after that it will be not possible to withdraw ether from balance using `withdrawEtherBalance` function.
## Vulnerability Detail
In case, when it was not possible to leverage/deleverage to the target level, then target level [is set to the `twapLeverageRatio` variable](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L1169-L1171), so later users can continue rebalancing using `iterateRebalance` function. Also `twapLeverageRatio` variable [can be deleted](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L1183-L1185) in this function.

In case when operator wants to repay whole loan to upgrade contract or shut down strategy, then he can call `disengage` function. After that SetToken will not have debt in aave as it will fully repay it in this function.

`AaveLeverageStrategyExtension` is going to contain ether balance, which is used to pay users for rebalancing. Operator can call `withdrawEtherBalance` function in order to withdraw funds. It is possible only when `twapLeverageRatio == 0`, as `noRebalanceInProgress` modifier is used.

So now i am ready to explain possible problem.
In case if `twapLeverageRatio != 0`(active rebalancing) an operator calls `disengage` in order to shut down strategy, then it is not possible for him to call `withdrawEtherBalance` function in order to withdraw ether from extension.
The only solution to remove `twapLeverageRatio` is to call `iterateRebalance` function. But it will fail, once whole debt is repaid. Because, [`_getAndValidateLeveragedInfo` function](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L339-L343) requires [that debt is not 0](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L867).
## Impact
It is not possible to withdraw balance from extension contract.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
Maybe, you need to delete `twapLeverageRatio` when debt is fully repaid.

**Comment by rvierdiyev** [comment]
Escalate for 10 usdc.
I think it was wrongly excluded.

**Comment by 0xffff11** [comment]
Thanks @rvierdiyev I would like to know if the operator won't be able to withdraw for a specific period of time, or it will be a full DOS without being able to withdraw ever?

**Comment by rvierdiyev** [comment]
> The only solution to remove twapLeverageRatio is to call iterateRebalance function. But it will fail, once whole debt is repaid

that means that in described situation it will be stuck forever

**Comment by 0xffff11** [comment]
In that case, this could be considered a medium. @ckoopmann

**Comment by ckoopmann** [comment]
Generally valid. Although I'm not sure if the funds would really be stuck forever since the operator could just call `engage` again and then probably reach a state where the `twapLeverageRatio = 0`

Either way we have already added functionality for the operator to override this check as a remediation to a different issue which should also fix this one:

https://github.com/sherlock-audit/2023-05-Index-judging/issues/10

**Comment by hrishibhat** [comment]
@rvierdiyev 
> Although I'm not sure if the funds would really be stuck forever since the operator could just call engage again and then probably reach a state where the twapLeverageRatio = 0

Any further comments? This would be a temporary DOS in that case and no loss of funds.

**Comment by rvierdiiev** [comment]
> Although I'm not sure if the funds would really be stuck forever since the operator could just call engage again and then probably reach a state where the twapLeverageRatio = 0

So in order to do that owner will need to engage and do some rebalancing, which means that he needs to provide funds to aave again and do rebalancing to reach twapLeverageRatio = 0. This is additional harm and i am not sure if it's possible do to eventually and how many iterations will be needed. Also as owner decided to shutdown strategy, that means that launch it again can be not desired in this situation.

**Comment by hrishibhat** [comment]
@rvierdiyev 
From another perspective pointed out by the lead watson, the manager would have to make the mistake of disengaging when there was an active rebalance happening which would mean an admin error.

**Comment by hrishibhat** [comment]
@ckoopmann 
> So in order to do that owner will need to engage and do some rebalancing, which means that he needs to provide funds to aave again and do rebalancing to reach twapLeverageRatio = 0. This is additional harm and i am not sure if it's possible do to eventually and how many iterations will be needed. Also as owner decided to shutdown strategy, that means that launch it again can be not desired in this situation

Can you comment on this?

Also let me know what you think of this comment:
https://github.com/sherlock-audit/2023-05-Index-judging/issues/71#issuecomment-1631851436

**Comment by ckoopmann** [comment]
> This is additional harm

Comments seem to be factually correct. 
Will leave the decision on validity / severity of this to the lead watsons / judges.

As mentioned above this is already fixed in a post audit adjustment (lmk if you disagree), so we wont deploy any additional fixes for this one.

**Comment by rvierdiiev** [comment]
@hrishibhat 
>From another perspective pointed out by the lead watson, the manager would have to make the mistake of disengaging when there was an active rebalance happening which would mean an admin error.

i don't think it's admin error
>In case when operator wants to repay whole loan to upgrade contract or shut down strategy, then he can call disengage function. After that SetToken will not have debt in aave as it will fully repay it in this function.

it's not error, when admin decided to shut down strategy 
he definitely can decide to do that, while active rebalance happening. as otherwise he needs to spend more time waiting.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
> he definitely can decide to do that, while active rebalance happening.

This would still be an admin error, and although inconvenient the dos is not permanent. Based on all the comments above considering this a low

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [rvierdiyev](https://github.com/sherlock-audit/2023-05-Index-judging/issues/71/#issuecomment-1610934035): rejected
