### ISSUE TITLE
rvierdiiev - Users still can call rebalance/iterateRebalance after disengage is called

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#73]
rvierdiiev

medium

# Users still can call rebalance/iterateRebalance after disengage is called

## Summary
Users still can call rebalance/iterateRebalance after disengage that doesn't repaid full debt is called, because it doesn't clear state.
## Vulnerability Detail
When operator calls `disengage` that means that he wants to shut down strategy an fully repay debt.
It's possible that he will not be able to do that [through the one step](https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L426-L430). In this case it will be needed to call `disengage` several times.

`disengage` function doesn't make any state changes to the contract. Because of that users are still able to call `rebalance`/`iterateRebalance` function. In case if this rebalancing will be done in lever side, this will not help operator to delever positions.

Example.
1.`twapLeverageRatio` is not 0, so `iterateRebalance` can be called.
2.operator calls `disengage`, and does partial delever.
3.any user calls `iterateRebalance` and make lever again.
4.as result user can make problems for operator to make full deleverage.
## Impact
Users still allowed to lever position
## Code Snippet
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-coop-smart-contracts/contracts/adapters/AaveLeverageStrategyExtension.sol#L412-L438
## Tool used

Manual Review

## Recommendation
Maybe there is a need to add some global state variable that pauses users ability to call functions, when `disengage` is called.

**Comment by rvierdiyev** [comment]
Escalate for 10 usdc.
I think it was wrongly excluded.

**Comment by IAm0x52** [comment]
Low. Operators should be assumed to be aligned with the manager and wouldn't be actively fighting the manager as they attempt to disengage. Worst case if the operator was being malicious then the manager would just remove them.

**Comment by ckoopmann** [comment]
Seems to be duplicate of: https://github.com/sherlock-audit/2023-05-Index-judging/issues/137#issuecomment-1652714474

Agree with low severity

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low based on above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [rvierdiyev](https://github.com/sherlock-audit/2023-05-Index-judging/issues/73/#issuecomment-1610933860): rejected
