### ISSUE TITLE
shogoki - Missing Check for eMode side effects in certain functions

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#83]
shogoki

medium

# Missing Check for eMode side effects in certain functions

## Summary

The `AaveV3LeverageModule` allows the manager to set an eMode category. However this can lead to various unwanted side effects, which are not checked or accounted for.

## Vulnerability Detail

From [AAVE docs](https://docs.aave.com/developers/whats-new/efficiency-mode-emode):

> The protocol allows user to set the user eMode category to any of the eModeCategories configured by the PoolConfigurator given the following conditions holds true:
>
> - all the borrowed assets of the user are in the chosen category.
> - changing eMode doesn’t leave user position under-collateralised

Given this, it might be a problem, that when activating eMode there is no check, if the SetToken already has borrowed Assets outside the eMode category or is using assets outside the category as collateral. When activating the eMode inside `AaveV3LeverageModule` there is no check to account for that. However, this might not be a big deal as the call to AAVE will revert.

But there´s more to it. As there is no check for the assets enabled in the module to fit the eMode category, we can imagine that eMode was able to get activated, but in our list of `collateralAssetEnabled` or `borrowAssetEnabled` we still have other assets.

It is also possible that new assets, which are not compliant with the eMode category, are added after the eMode was already activated, using the `addBorrowAssets` and `addCollateralAssets` functions.

This will result in future deposits might not counted correctly as collateral, and borrows of these assets to fail.

## Impact

- Deposits might not count as collateral as expected
- Borrows might fail 
- Misconfiguration of SetToken, because Assets are enabled which are not supported by eMode category.

## Code Snippet

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L566-L568

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L607-L619

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L637-L649

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L987-L998

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol#L1004-L1014

## Tool used

Manual Review

## Recommendation

Checks should be implemented for the eMode category of the ReserveAssets.
The ReserveTokens struct could be extended to hold the category:

```solidity
 struct ReserveTokens {
        IAToken aToken;                         // Reserve's aToken instance
        IVariableDebtToken variableDebtToken;   // Reserve's variable debt token instance
        uint256 eModeCategory;                  // Reserve´s eModeCategory
    }
```

and the category be fetched like this:

```solidity
      IAaveProtocolDataProvider.TokenData[] memory reserveTokens = _protocolDataProvider.getAllReservesTokens();
        for(uint256 i = 0; i < reserveTokens.length; i++) { 
            (address aToken, , address variableDebtToken) = _protocolDataProvider.getReserveTokensAddresses(reserveTokens[i].tokenAddress);
            uint256 eModeCategory = _protocolDataProvider.getReserveEModeCategory(reserveTokens[i].tokenAddress);
            underlyingToReserveTokens[IERC20(reserveTokens[i].tokenAddress)] = ReserveTokens(IAToken(aToken), IVariableDebtToken(variableDebtToken), eModeCategory);
        }
```

- When the eMode category will be changed there should be a check if all enabled assets are belonging to the eMode category.

```solidity
 function setEModeCategory(ISetToken _setToken, uint8 _categoryId) external onlyManagerAndValidSet(_setToken) {
        if(_categoryId > 0) //no check required for 0 category {
            address[] memory _collAssets = enabledAssets[_setToken].collateralAssets;
            for(uint i= 0; i < _collAssets.length; i++) {
                require(underlyingToReserveTokens[IERC20(_collAssets[i])].eModeCategory == _categoryId, "Unsupported Category Id");
            } 
            address[] memory _borrowAssets = enabledAssets[_setToken].borrowAssets;
            for(uint i= 0; i < _borrowAssets.length; i++) {
                require(underlyingToReserveTokens[IERC20(_borrowAssets[i])].eModeCategory == _categoryId, "Unsupported Category Id");
            } 
        }
        _setToken.invokeSetUserEMode(IPool(lendingPoolAddressesProvider.getPool()), _categoryId);
    }
``` 

- When new assets will be added, there should be check that they belong to the currently set eMode category.

**Comment by Shogoki** [comment]
Escalate for 10USDC
This should be considered a duplicate of #251

**Comment by stalinMacias** [comment]
I don't think this is a duplicate of #251 , the issue reported here is about the asset's restriction when eMode is activated, and the issue reported on #251 is about the percentages that are used in AAVE for liquidations, those are two totally different things, plus, there is not an impact on users depositing assets if eMode is activated, those assets won't get stuck or lost, they won't simply count as collateral, and that doesn't affect the internal accounting of the setTokens.
Actually, this issue is similar to this #95, which should also not be a duplicate of #251, and none of these two issues causes a damage to the users.

**Comment by Shogoki** [comment]
I agree.
Deleted the escalation
