### ISSUE TITLE
saidam017 - Isolated assets could not work properly on Set Token with Aave leverage strategy

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#93]
saidam017

high

# Isolated assets could not work properly on Set Token with Aave leverage strategy

## Summary

If set token already have non-isolated aToken position on Aave, then supplying isolated asset to Aave for leverage strategy, the supplied asset will only set to earning yield but not as collateral. This will make `AaveV3LeverageModule` will not work properly.

## Vulnerability Detail

[Aave docs about Isolation mode](https://docs.aave.com/developers/whats-new/isolation-mode) : 

"Borrower in Isolation Mode cannot enable any other assets including the other isolated assets as collateral."

These check will prevent the supplied asset to be used as collateral : 

https://github.com/aave/aave-v3-core/blob/master/contracts/protocol/libraries/logic/SupplyLogic.sol#L78-L83

This could lead to 2 issue : 

1. If set token already have non-isolated aToken position on Aave, then supplying isolated asset to Aave for leverage strategy, the supplied asset will only set to earning yield but not as collateral.
2. First set token supply asset with isolated asset, then try to interact with non-isolated asset, then the non-isolated asset can't be used as collateral.

## Impact

 This will make Set token that use `AaveV3LeverageModule` will not work properly when handling aToken positions that contain isolation mode.

## Code Snippet

https://github.com/aave/aave-v3-core/blob/master/contracts/protocol/libraries/logic/SupplyLogic.sol#L78-L83
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol

## Tool used

Manual Review

## Recommendation

Depend on strategy, consider to reject isolated assets if already use non-isolated assets. Or check if the supplied asset is set as collateral after supplied.

**Comment by said017** [comment]
Escalated for 10 USDC

I still think this is valid concern with the mentioned explanation and risk.

**Comment by Evert0x** [comment]
Somewhat similar as #164, @0xffff11 thoughts?

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Based on the discussion in #164 considering this issue a low
https://github.com/sherlock-audit/2023-05-Index-judging/issues/164#issuecomment-1656107885

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [said017](https://github.com/sherlock-audit/2023-05-Index-judging/issues/93/#issuecomment-1610046653): rejected
