### ISSUE TITLE
saidam017 - Siloed assets borrowed on Set Token AaveV3LeverageModule could cause problem

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#94]
saidam017

medium

# Siloed assets borrowed on Set Token AaveV3LeverageModule could cause problem

## Summary

If an asset is configured as siloed, it can't be borrowed in a position at the same time as with other assets. This could lead to unexpected behavior for `AaveV3LeverageModule` and `DebtIssuanceModule` that require borrow on other asset when withdraw.

## Vulnerability Detail

[Aave V3 docs on siloed borrow](https://docs.aave.com/developers/whats-new/siloed-borrowing) : 

"A user borrowing a siloed asset can't borrow the siloed asset in a position at the same time as borrowing other assets." 

With this behavior, using asset with siloed borrow on set Token that have AaveV3Leverage and debt issuance for multiple asset could not work properly.

For instance, debt issuance rely on borrow when issue a token : 

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/DebtIssuanceModule.sol#L677-L697

```solidity
    function _executeExternalPositionHooks(
        ISetToken _setToken,
        uint256 _setTokenQuantity,
        IERC20 _component,
        bool _isIssue,
        bool _isEquity
    )
        internal
    {
        address[] memory externalPositionModules = _setToken.getExternalPositionModules(address(_component));
        uint256 modulesLength = externalPositionModules.length;
        if (_isIssue) {
            for (uint256 i = 0; i < modulesLength; i++) {
                IModuleIssuanceHook(externalPositionModules[i]).componentIssueHook(_setToken, _setTokenQuantity, _component, _isEquity);
            }
        } else {
            for (uint256 i = 0; i < modulesLength; i++) {
                IModuleIssuanceHook(externalPositionModules[i]).componentRedeemHook(_setToken, _setTokenQuantity, _component, _isEquity);
            }
        }
    }
```

## Impact

SetToken that use `AaveV3LeverageModule` and `DebtIssuanceModule` could not work properly, especially if it using functions that depend on borrow multiple asset.

## Code Snippet

https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AaveV3LeverageModule.sol
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/DebtIssuanceModuleV2.sol
https://github.com/sherlock-audit/2023-05-Index/blob/main/index-protocol/contracts/protocol/modules/v1/DebtIssuanceModule.sol

## Tool used

Manual Review

## Recommendation

Consider to not allow siloed borrow, or make it explicit (create parameter e.g `isAllowSiloed`) when create the leverage strategy to make sure if user want to interact with siloed asset.

Duplicate of #269

**Comment by said017** [comment]
Escalated for 10 USDC

I still think this is valid concern with the mentioned explanation and risk.
