### ISSUE TITLE
jasonxiale - Unbounded loop may cause denial of service due to maximum gas limit reached

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-Index-judging#97]
jasonxiale

medium

# Unbounded loop may cause denial of service due to maximum gas limit reached

## Summary
Unbounded loop may cause denial of service due to maximum gas limit reached.
Malicious actor can  **permissionlessly** repeat creating `SetToken` by calling [SetTokenCreator.create](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/SetTokenCreator.sol#L66-L73), lots of `SetToken` is added into [controller's set](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/Controller.sol#L67). 
After that, if the protocol owner wants to call [Controller.removeSet](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/Controller.sol#LL175C14-L175C23) to remove a SetToken, the `removeSet` function will iterate tons of SetToken created by malicious actor to find the matching one, which might run out of gas

## Vulnerability Detail

Within [Controller.addSet](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/Controller.sol#LL160C1-L169C1), the `_setToken` is pushed into `sets` array
```solidity
    function addSet(address _setToken) external onlyInitialized onlyFactory {
        require(!isSet[_setToken], "Set already exists");

        isSet[_setToken] = true;

        sets.push(_setToken);

        emit SetAdded(_setToken, msg.sender);
    }
```

And when calling [Controller.removeSet](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/Controller.sol#L175C14-L183) to remove an `SetToken` from the `sets`, function **remove** is called
```solidity
    function removeSet(address _setToken) external onlyInitialized onlyOwner {
        require(isSet[_setToken], "Set does not exist");

        sets = sets.remove(_setToken);

        isSet[_setToken] = false;

        emit SetRemoved(_setToken);
    }
```

In the function [AddressArrayUtils.remove](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/lib/AddressArrayUtils.sol#L84-L96) `indexOf` is called
```solidity
    function remove(address[] memory A, address a)
        internal
        pure
        returns (address[] memory)
    {
        (uint256 index, bool isIn) = indexOf(A, a);
        if (!isIn) {
            revert("Address not in array.");
        } else {
            (address[] memory _A,) = pop(A, index);
            return _A;
        }
    }
```

And in [AddressArrayUtils.indexOf](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/lib/AddressArrayUtils.sol#L39C14-L47), the function will iterate the array to find the matched element
```solidity
    function indexOf(address[] memory A, address a) internal pure returns (uint256, bool) {
        uint256 length = A.length;
        for (uint256 i = 0; i < length; i++) {
            if (A[i] == a) {
                return (i, true);
            }
        }
        return (uint256(-1), false);
    }
```

## Impact
Unbounded loop may cause denial of service due to maximum gas limit reached.
## Tool used

Manual Review

**Comment by crazy4linux** [comment]
Escalate for 10 USDC

This is a valid issue since [controller's set](https://github.com/sherlock-audit/2023-05-Index/blob/3190057afd3085143a31746d65045a0d1bacc78c/index-protocol/contracts/protocol/Controller.sol#L67) can be added by anyone, and when removing element from the **set**, the `remove` function will iterate the array to find the element, which might be DOSed

**Comment by 0xffff11** [comment]
Owner can remove after. Adding all of this worthless setTokens to the array also costs a lot of gas. I do not see the real impact here. This does not break any core functionality of the protocol. Still think that if having no access control has no benefits on the function, it should have a modifier to restrict access. Low

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with Lead judge comments. Considering this issue a valid low as there is no severe impact of this issue
